### ISSUE TITLE
[Proposal] Exposure schema to also include calculation method

### ISSUE THREAD

**Issue by matamadio** [GFDRR/rdl-standard#10]
## What is the context or reason for the change?

Following #4, I was thinking that the same "calculation method" attribute could be applied to E models to help discriminate their type. Exposure model can be obtained by direct observation (e.g. buildings location and footprins collected via GPS, drones, sats), inferred (e.g. population density map derived from land cover data); there could be even cases where the exposed variable is entirely simulated, but most simulations are based on a remote sensing proxy, falling into the "inferred" category.

## Why is this not covered by the existing model?

No specific attribute convey this type of information. It could be inferred from a the type of resource (e.g. "satellite" data implies observation, "scenario" implies modelling), but that may not be always obvious/univocal.

## What is your proposed change?

Please describe the change(s) you are proposing. Please provide a name and a clear definition for and new or revised attributes or relationships, along with expected values.

Add the following mandatory attribute to exposure model: 

| exp.calc_method |
| -- |
| Observed |
| Inferred |
| (Simulated?)|

**Comment by stufraser1** [comment]
Often EXP datasets are developed as a combination of ground/field mapping, and simulation of building location and occ/constr type based on that field mapping combined with EO data. So the distinction may not be possible or clearly attributable to just one - unless there is an option for the combination. I believed the structure allowed for defining the method of development, but perhaps this was not enum type but in exposure_model.description.

**Comment by matamadio** [comment]
Agreed this should be aligned with attributes commonly found in exposure layer.
Which is not the case for the proposed enum.
Agreed to keep it as optional part of model description.
