### ISSUE TITLE
[Proposal] Provide machine-readable files for all RDL code lists

### ISSUE THREAD

**Issue by ldodds** [GFDRR/rdl-standard#11]
## What is the context or reason for the change?

RDL defines a number of codelists for use in filed like `hazard_type`, `process_type`, etc. Copies of these are includes in the project documentation and also the SQL in the [rdl-data](https://github.com/GFDRR/rdl-data/tree/master/sql) project. 

But they are not published as standalone, machine-readable files that can be referenced and used by different applications.

Also, some code lists, e.g. `calc_method` and `occupancy` are simple lists of strings. While others like `hazard_type` and `process_type` are a list of codes and names. Ideally all entries would have a standard code, a name and a description.

## What is your proposed change?

* Create a `specs/code-lists` folder in this project to store machine-readable code lists in CSV format
* Use a consistent core schema for each code list, so that each code lists consists of a table that has three colums: `code`, `label` and `definition`. Where `code` is a unique code/label for the entry, `label` is a human-readable label` and `definition` describes that the code means
* More complex code lists can include additional columns, e.g. to point to related terms, or cross-link between taxonomies

These has the benefits that:

* code list files can then be linked to from public documentation, so they can be imported and used by tools and applications
* the code lists can be consistently referenced from different schemas, e.g. from the SQL database and from the data package formats.
* human-readable versions of the CSV files can still be included in documentation, e.g. [as Open Contracting do](https://standard.open-contracting.org/1.1/en/schema/codelists/#)
* the files will be versioned alongside the other specifications, making it clearer when they are revised or changed
* the `code` column provides a unique reference for individual entries allowing labels to be translated and revised without impacting applications that use them
* the `code` column provides a stable identifier to allow mapping between taxonomies

## Can you provide an example?

This is consistent with how projects like Open Contracting are documenting their code lists. [See example here](https://github.com/open-contracting/standard/tree/1.1-dev/schema/codelists). 

I've suggested slightly different column names to align with [the SKOS standard](https://www.w3.org/TR/skos-reference/) for defining code lists and taxonomies.

**Comment by jeanpommier** [comment]
@ldodds I was indeed thinking of using SKOS RDF format. For AFAIK it is XML files.
SKOS RDF allows for internationalization. How would you suggest it using CSV files ?

**Comment by ldodds** [comment]
@jeanpommier SKOS can be represented using an RDF serialisation. The FAO publish AgroVoc as ntriples, for example rather than RDF/XML which not that many people use these days. 

I was thinking of keeping it simple initially and just using a CSV format because that would be easier for people to use in common tools. But its also relatively simple to convert into a more complex structure if needed in future. So wasn't thinking about a complete mapping of SKOS to CSV, but keep that option open if needed in future.

**Comment by matamadio** [comment]
Thanks both; actually this is similar to how we [implemented it in jkan ](https://github.com/GFDRR/rdl-jkan/tree/gh-pages/_data) for adding data via form, each option item has its own yaml file, but in most case it is just one column.
Agree to set them as csv with columns `code`, `label` and `definition` and suggest to store them in the rdl-standard repo.

**Comment by stufraser1** [comment]
@odscrachel @odscjen - please confirm whether this will happen in this schema update?

**Comment by odscrachel** [comment]
@stufraser1 Yes, this will be done in the schema update
