### ISSUE TITLE
[Proposal] impact_metric.csv codelist for Vulnerability impact metric

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdl-standard#125]
branching off from https://github.com/GFDRR/rdl-standard/issues/75, the impact_metric.csv codelist needs populated with descriptions and if necessary any extra codes.

Current codes are

Code | Title
damage ratio | Damage ratio
mean damage ratio	| Mean damage ratio
probability of exceeding damage limit state | Probability of exceeding damage limit state
loss ratio | Loss ratio
total loss | total loss
number of casualties(fatalities) | Number of casualties (fatalities)
casualty(fatality) ratio | Casualty (fatality) ratio
annual average loss | Annual average loss
downtime | Downtime
damage index | Damage index

**Comment by stufraser1** [comment]
These impact metric codes relate to those used on the y-axis in vulnerability functions and fragility functions:
Code,Title,Description
damage_ratio,Damage ratio,The estimated repair cost of an asset divided by the total replacement cost of the asset [0-n] used in vulnerability functions.
mean_damage_ratio,Mean damage ratio,The mean value in a distribution of estimated repair costs divided by the total replacement cost of an asset [0-n] used in vulnerability functions.
probability,Probability,The probability of reaching or exceeding a damage limit state specified in a fragility function [%].
damage_index,Damage index,"A specified index or classification of damage levels, which may be numeric or non-numeric."
loss_ratio,Loss ratio,"The loss to an asset divided by the total replacement cost of the asset [0-n] as a function of damage state, used in damage-to-loss-models."
mean_loss_ratio,Mean Loss Ratio,"The mean loss ratio in a distribution of losses divided by the total replacement cost of the asset [0-n] as a function of damage state, used in damage-to-loss-models."
downtime,Downtime,"Duration of downtime, used in vulnerability modelling of business or service interruption."
casualty_ratio,Casualty ratio,"The number of expected casualties or fatalities as a proportion of total inhabitants of and asset or population [0-1] used in casualty or mortality functions."
_______________

Engineering demand functions have a set of structural response value used on y-axis, contained in edp_name.csv 

_______________


These codes are used in the loss component to describe **loss metrics**:
economic_loss,Total Loss,The monetary value of estimated economic impact or total loss (ground up loss in insurance terminology). Impact_type denotes whether this refers to total, direct, or indirect loss.
insured_loss,Total Loss,The monetary value of estimated insured losses.
loss_ratio,Loss Ratio,Estimated loss as a proportion of total replacement cost or insured value. Impact_type denotes whether this refers to total, direct, or indirect loss.
numCasualties,Number of casualties (fatalities),The estimated number of casualties or fatalities.
casualty_ratio,Casualty ratio,Proportion of estimated casualties or fatalities in the total population.
aal,Annual average loss,Expected loss over a one-year time period according to long-term averages. Impact_type denotes whether this refers to total, direct, or indirect loss.
pml,Probable Maximum Loss,Estimated maximum loss occurring at a given exceedance probability or return period.
var,Value at Risk,Estimated minimum loss likely to be equalled or exceeded in a given year for a given probability.
tvar,Tail Value at Risk,Estimated losses at or exceeding a specified value at risk VaR (estimate of average losses given that a severity threshold has been exceeded).
downtime,Downtime,"Duration of downtime (business or service interruption)."
