### ISSUE TITLE
[Proposal] update descriptions in process_type.csv

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdl-standard#136]
## What is the context or reason for the change?

Descriptions for all the codes in process_type.csv had to be created from scratch. Due to time constraints these have not been thoroughly reviewed and a couple of definitions are incomplete. From the original issue #112

"Updated descriptions for process_type.
Largely using UNDRR Hazard terminology as the basis (included citations come from that document) and we should reflect this as the source in the overall documentation.

**We need to confirm the difference between primary and secondary rupture.
We need to confirm whether we need code MHC, given we discussed putting multiple process types together in a string.**
I added 3 specific landslide types."

**Comment by stufraser1** [comment]
@pslh do you recall the reasoning for including process_type='primary rupture' AND process_type='secondary rupture' and would there be a definition for secondary rupture that distinguishes it from primary rupture, maybe used by GEM, that we could use here?

**Comment by odscjen** [comment]
closed by #222
