### ISSUE TITLE
[Docs update] GLIDE number

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdl-standard#142]
## What is the context or reason for the change?

More info needed on rationale for GLIDE number, ability to use other disaster identifiers
E.g. Shakemap ID for EQ
Consider limitations on GLIDE hazard code versus ours (shouldn't be restrictive, not explicitly linked in RDLS)

**Comment by odscjen** [comment]
From a technical standpoint there is potential to reuse the new `Classification` object here. this would allow users to declare which scheme they're taking their disaster id from, e.g.:

```json

"disaster_identifer": {
  "id": "ak0238v9wqev",
  "scheme": "Shakemap ID",
  "description": "M 3.4 - 15 km ESE of Eagle River, Alaska"
  "uri": "https://earthquake.usgs.gov/data/shakemap/"
}
```

the scheme's that it's possible to use could be added to the `classification_scheme.csv` codelist which is open.

**Comment by matamadio** [comment]
While I support the GLIDE as the "standardiest" reference for empirical events, I agree on the approach suggested by Jen.

**Comment by stufraser1** [comment]
GLIDE / disaster_id is referenced the schema reference, which would be captured in changes made under #221

It is also referenced under 
https://rdl-standard.readthedocs.io/en/dev/rdl/other-standards/#hazard-data-standards
Options - 
- remove this
- shorten this
- add description of PAGER ID as an alternative ID

**Comment by stufraser1** [comment]
removed - text here for reference, for partial use in codelist description

**GLIDE disaster event identifier**:
Since the beginning of 2004, GLobal IDEntifier numbers (GLIDE) are produced at (GLIDEnumber.net) for all new disaster events reported by partner institutions and those discovered by ADRC.
A GLIDE number comprises two letters to identify the disaster type (e.g. EQ - earthquake); the year of the disaster; a six-digit, sequential disaster number; and the three-letter ISO code for country of occurrence. E.g., the GLIDE number for West-India Earthquake in India is: EQ-2001-000033-IND. This number is posted by the above organizations and in many other websites, on their documents relating to that particular disaster and gradually other partners will include it in whatever information they generate. As information suppliers join in this initiative, documents and data pertaining to specific events may be easily retrieved from various sources, or linked together using the unique GLIDE numbers. List of services using GLIDE: https://glidenumber.net/glide/public/links.jsp
The RDL Standard uses a GLIDE number in the `hazard.event` object, to denote the historical event to which hazard event data relates, e.g., the simulated hazard intensity footprint of that event.
