### ISSUE TITLE
Choose a version number

### ISSUE THREAD

**Issue by duncandewhurst** [GFDRR/rdl-standard#145]
Currently, the RDLS lacks a formal version number, althogh the name of schema file (`rdl_schema_0.1.json`) implies version 0.1. The technical review recommends implementing [semantic versioning](https://docs.google.com/document/d/1dBK7dr7JzHnLwcR9RTHybjpaS8JViopu5LLGPHqpm2c/edit#heading=h.v6kq1jtsrh42), which involves choosing an initial version number.

I think that the standard should remain on major version zero (0.Y.Z), which is for initial development and communicates that anything may change at any time. I think that the current informal version number should be incremented to communicate that there have been significant changes to the schema. Therefore, my recommended version number is 0.2.

The alternative would be to release version 1.0. However, moving to major version 1.0 means that future changes to the standard must be versioned semantically (backward compatible changes only for minor version numbers, e.g. 1.1) and implies a supporting change control and governance process, which has not yet been developed or documented. Remaining on major version zero allows for flexibility in making further changes in response to learnings from early implementation. Comparable standards are also on major version zero, e.g. the [Beneficial Ownership Data Standard](https://standard.openownership.org/en/0.3.0/) and the [Open Fibre Data Standard](https://open-fibre-data-standard.readthedocs.io/en/latest/).

**Comment by stufraser1** [comment]
Agree with all this. 0.2 makes the most sense
