### ISSUE TITLE
[Proposal] Occupancy and asset types should be common tables adopted by all schemas

### ISSUE THREAD

**Issue by matamadio** [GFDRR/rdl-standard#15]
Tables should not overlap, should not share same definitions.**

Now we have one common ENUM for occupancy:

cf_common.occupancy_enum
--
Residential
Commercial
Industrial
Infrastructure
Healthcare
Educational
Government
Crop
Livestock
Forestry
Mixed

(Note: using "Mixed" for unspecified or total occupancy is misleading. Suggest to add "All", "General" or "Total" to this list.)
The E schema uses this common ENUM in conjunction with "Asset type" defined by _ged4all.category_enum_.

ged4all.category_enum
--
buildings
indicators
infrastructure
crops, livestock and forestry

Here there is a bit of overlapping on "crops, livestock and forestry" that can generate confusion. Since occupancy defines the type of crop,livestoc&forestry, the category type could just be "land cover", "land use area" or similar.
Also, this category_enum should be made common table as it applies also to V and L schemas.
The V schemas gets the "occupancy" from common tables and then "asset type" from H schema, but doesn't include "category".

Then, there is the L schema using _loss.component_enum_ to define the type of losses; 

loss.component_enum
--
Buildings
Direct Damage to other Asset
Contents
Business Interruption

Here "Buildings" should instead be "Structure", opposed to "Content".
But both represent "Direct damage to asset", opposed to "Indirect losses", which include "Business interruption" but also other types of indirect impacts (e.g. stock depletion, re-routing of investments, etc).
Needs to become more consistent. Also "component" is a word we use to indicate each part of the schema (component H, componen E, etc);

Proposal:
```
loss.element_enum
--
Structure
Content
Business Interruption

loss.impact_enum
--
Direct
Indirect
```

**Comment by stufraser1** [comment]
cf_common.occupancy_enum

For infrastructure to be at the same level as the buildings in this table, (res/com/ind/edu/gov/hlth), it may be better to use types / sectors of infrastructure: water, energy, transport, communications; which in turn would sit under the infrastructure category in category_enum

**Comment by stufraser1** [comment]
ged4all.category_enum

Agree crop, livestock, forestry is specified already in occupancy_enum. If it is to be an overarching category, then I agree it should be changed - 'agriculture' comprising livestock and crop, and 'environment' comprising forestry - for now

**Comment by stufraser1** [comment]
Resolved by changes being made in JSON schema
