### ISSUE TITLE
[Docs update] Create content for Vulnerability and Loss taxonomy sections

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdl-standard#150]
Create content for the [vulnerability](https://rdl-standard.readthedocs.io/en/dev/taxonomies/#vulnerability-taxonomies) and [Loss](https://rdl-standard.readthedocs.io/en/dev/taxonomies/#loss-taxonomies) taxonomy sections. There are currently empty

**Comment by matamadio** [comment]
We don't have any taxonomy available / adopted for these two components, for now.

**Comment by odscjen** [comment]
That's fine, in that case I'd recommend updating the sections to explain this just in a sentence or two.

**Comment by odscjen** [comment]
closing this as the restructure in #175 has removed the taxonomy page and the content that was there about Vulnerability and Loss has been updated from holding sentences
