### ISSUE TITLE
[Docs update] Ensure manage.py is adding the correct references to the sub-schema and codelist references

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdl-standard#151]
Ensure `.manage.py` is adding the correct references to the sub-schema and codelist references

**Comment by odscjen** [comment]
Assigning this to you @duncandewhurst as you commented out previous parts of `.manage.py` that I think are now ready to be used again

**Comment by duncandewhurst** [comment]
Sounds good. I'll do this once https://github.com/GFDRR/rdl-standard/issues/167 is done, since that might affect the script.
