### ISSUE TITLE
[Taxonomies] Add explanation to Hazard taxonomies section about RDL taxonomy becoming codelists

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdl-standard#155]
The RDL Hazard taxonomy has been shifted into a pair of codelists, add a sentence or two explaining this to [Hazard taxonomies](https://rdl-standard.readthedocs.io/en/dev/taxonomies/#hazard-taxonomies) section.

**Comment by matamadio** [comment]
The current text fits the purpose, with some edits to make clear we have our taxonomy as derived from existing ones:

> The RDL project performed a review of the most relevant hazard taxonomies and derived a classification focusing on those hazards and processes that are more often required in disaster risk assessments, while mapping and matching alternative definitions into one consistent framework.
> 
> [codelist table]
> 
> There are several existing taxonomies that have been considered to classify hazard data into one consistent list:

**Comment by matamadio** [comment]
The current text fits the purpose, with some edits to make clear we have our taxonomy as derived from existing ones:

> The RDL hazard taxonomy can accommodate most natural hazard types and processes. The RDL project performed a review of the most relevant hazard taxonomies and derived a classification focusing on those hazards and processes that are more often required in disaster risk assessments, while mapping and matching alternative definitions into one consistent framework.
> 
> [codelist table]
> 
> There are several existing taxonomies that have been considered to classify hazard data into one consistent list:

**Comment by odscjen** [comment]
Closing as the restructure in #175 provides this clarity
