### ISSUE TITLE
[Docs update] Remove GED4all exposure taxonomy page

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdl-standard#159]
it’s basically just repeating the information that's on the GED4all webpage and this is creating an extra unnecessary thing to keep up-to-date with the risk of it going out of sync.

**Comment by odscjen** [comment]
Unlikely to work on this in this dev cycle

**Comment by matamadio** [comment]
Would the alternative be to just point usert to GED4all website?
Also note the GED4all schema hasn't been updated in ages, so virtually no risk of being unaligned.

**Comment by odscjen** [comment]
Yes that would be the ideal way of doing it
