### ISSUE TITLE
[Docs update] Review for content that would be better place in the RDL website than the RDLS documentation

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdl-standard#160]
Consider what can be taken out of the RDLS documentation and instead hosted on the RDL pages, i.e. guidance that relates to the general RDL but isn’t strictly related to the standard schema.

**Comment by odscjen** [comment]
Unlikely to be work on in this dev cycle

**Comment by duncandewhurst** [comment]
Closing since this has been addressed by clarifying the scope of RDLS and clearly separating the guidance related to publishing risk datasets from the other (metadata-related) content.
