### ISSUE TITLE
[Spreadsheet template] Create repository

### ISSUE THREAD

**Issue by duncandewhurst** [GFDRR/rdl-standard#166]
@stufraser1 @matamadio please could you create a repository for the spreadsheet template (e.g. rdls-spreadsheet-template) under the GFDRR organisation and grant me owner permissions?

We can then use that repository to store the template and the command-line tool to generate it and we can use the repository's issue tracker to keep issues about the spreadsheet template separate from issues about the standard itself.

**Comment by stufraser1** [comment]
Created
https://github.com/GFDRR/rdls-spreadsheet-template
