### ISSUE TITLE
Embed refactored MOVER into combined schema

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdl-standard#17]
MOVER standalone include the pilot socioeconomic index/inidcators capability.
This needs to be embedded into the combined schema

**Comment by matamadio** [comment]
The capability for socio-economic indices has been added to the schema from v0.2.
V schema is now split into 2 independent schemas:
- VLN-PH: Physical vulnerability as represented by damage functions, hazard thresholds and similar models
- VLN-SE: Socio-Economic vulnerability as represented by wealth, poverty, and other indicators

![immagine](https://user-images.githubusercontent.com/44863827/214548131-c95180f9-d46f-46d6-a616-6e0d4bbdee46.png)
