### ISSUE TITLE
[Schema] Should the risk_data_type field be an array?

### ISSUE THREAD

**Issue by duncandewhurst** [GFDRR/rdl-standard#176]
@stufraser1 @matamadio, elsewhere I think we've established that a risk dataset can cover more than one type of risk data (hazard, exposure, vulnerability, loss). However, the top-level `risk_data_type` field is a string so it can only take one value from the [risk_data_type codelist](https://rdl-standard.readthedocs.io/en/dev/reference/codelists/#risk-data-type). Should we change the field's type to be an array so that it can take multiple values, e.g. hazard and exposure?

**Comment by matamadio** [comment]
I think the idea was to split datasets by risk data type, hence just one type per dataset.

**Comment by duncandewhurst** [comment]
Hmm, from the discussion about the spreadsheet template, my understanding was that we wanted to support datasets covering multiple types of risk data.

The change (if needed) is straightforward so we can wait for @stufraser1 to return from leave to get his input.

**Comment by johcarter** [comment]
It was also my understanding that you could have one or more risk data types in one package.  Certainly for a catastrophe model, you would have both hazard and vulnerability together under one dataset, and possibly also some exposure data for testing the model. If risk_data_type is not an array, the dataset info has to be repeated for each risk data type.  It would seem more flexible to allow risk_data_type to be an array, as you can still separate the datasets by risk_data_type if you wished.

**Comment by matamadio** [comment]
Noted.
Nothing should hold the user to choose wether or not to include multiple components when they share the exact same common metadata. However, when there are differences e.g. year, spatial extent, etc., then multiple dataset should be preferred.

**Comment by stufraser1** [comment]
We would like one or more risk data types in one package, which was a core aim of the standard - to provide more-connected data packages so `risk_data_type` should be an array.
Moving to agreed.
