### ISSUE TITLE
[Schema] Order fields

### ISSUE THREAD

**Issue by duncandewhurst** [GFDRR/rdl-standard#177]
In https://github.com/GFDRR/rdls-spreadsheet-template/issues/1#issuecomment-1666221996, @stufraser1 suggested applying a logical ordering to fields in the spreadsheet template, which are currently ordered by the order they appear in the schema.

We should apply the logical ordering in the schema so it appears in any resources that we generate from the schema, such as the schema browser and reference tables in the documentation.

@stufraser1 @matamadio do you want to propose an ordering or is that something that you would like ODS to take a first pass at?

**Comment by matamadio** [comment]
Order of tabs:
- Dataset
- Attribution
- Sources
- Referenced by
- Hazard tabs
- Exposure cost
- Vulnerability cost
- Vulnerability gazetteer
-  Loss cost
- Resources
- Spatial_gazetteer entries

The order of fields looks fine overall.

**Comment by duncandewhurst** [comment]
Since `resources` and `spatial_gazetteer_entries` are 'common' tabs, I think it would sense to have them appear before the component tabs. Otherwise, the b/w tabs will be split, with some appearing before the component tabs and some appearing after. Sound good?

**Comment by stufraser1** [comment]
All sounds good, moving to agreed.
