### ISSUE TITLE
[Docs update] Update or remove mermaid flowcharts

### ISSUE THREAD

**Issue by matamadio** [GFDRR/rdl-standard#178]
There is a chart generator plugin called mermaid that creates the schema flowcharts:

![immagine](https://github.com/GFDRR/rdl-standard/assets/44863827/ddc23665-f0b4-4163-bc12-93e7415e6ee5)

It's a bit bulky and doesn't reflect the current status of the schema.
It should be either:
- updated, ideally getting data from the json automatically
- replaced by better figures/plugin
- removed

**Comment by duncandewhurst** [comment]
Agree that the diagrams need to be updated or removed.

Whilst it might be possible to generate diagrams automatically from the schema, they would be extremely large and complex so some extra curation would be needed to decide which fields to include on the diagram.

I think a better approach would be generating diagrams from JSON examples of RDLS metadata (rather than from the schema). [PlantUML](https://plantuml.com/json) does quite a good job of generating diagrams from JSON data. For example, I generated a diagram that covers the same fields and relationships as the diagram in the issue description, but updated for the latest version of the schema:

**Diagram**
![image](https://github.com/GFDRR/rdl-standard/assets/19265814/770f76ae-d05d-4ea8-ad5a-9c565ee7d170)

**Input data**
```json
{
  "event_sets": [
    {
      "analysis_type": "",
      "events": [
        {
          "calculation_method": "",
          "hazard": {
            "type": "",
            "trigger": {}
          },
          "occurrence": {},
          "footprints": [
            {
              "intensity_measure": "",
              "data_uncertainty": ""
            },
            {
              "intensity_measure": "",
              "data_uncertainty": ""
            }
          ]
        },
 {
          "calculation_method": "",
          "hazard": {
            "type": "",
            "trigger": {}
          },
          "occurrence": {},
          "footprints": [
            {
              "intensity_measure": "",
              "data_uncertainty": ""
            },
            {
              "intensity_measure": "",
              "data_uncertainty": ""
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by matamadio** [comment]
Thanks, agree they should focus on the key connections rather than showing the whole set of attributes.
Agree to generate simplified json.

**Comment by duncandewhurst** [comment]
@matamadio in terms of next steps on this issue, are you happy to propose a subset of fields to include in each diagram and then we can draft the necessary JSON files and generate the diagrams?

**Comment by matamadio** [comment]
> @matamadio in terms of next steps on this issue, are you happy to propose a subset of fields to include in each diagram and then we can draft the necessary JSON files and generate the diagrams?

Yes please, diagram for each compontents as follows:

### Dataset (general) - all non specific attributes

- title
- description
- risk_data_type
- publisher
  - name
  - email
  - url
- version
- purpose
- project
- details
- spatial
  - countries
  - spatial/bbox
- license 

### Hazard

event_sets | events | footprints
-- | -- | --
analysis_type | description | intensity_measure
frequency_distribution | hazard/type | data_uncertainty
seasonality | hazard/processes |  
event_count | hazard/intensity_measure |  
occurrence_range | hazard/trigger |  
spatial | disaster_identifier |  
temporal | calculation_method |  
&nbsp; | occurrence |  

### Exposure

- category
- taxonomy
- metric
- cost
  - type
  - unit

### Vulnerability

- hazard_primary
- hazard_analysis_type
- intensity
- category
- impact
  - type
  - metric
  - unit
- functions (only list types)
  - vulnerability
  - fragility
  - damage_to_loss
  - engineering_demand
  - se_category
- analysis_details
- temporal_resolution

### Loss

- hazard_type
- hazard_process
- category
- type
- impact
  - type
  - metric
  - unit
- approach
- cost
  - type
  - unit

Please mark required or optional fields.

**Comment by duncandewhurst** [comment]
> Please mark required or optional fields.

We can use PlantUML's [highlighting feature](https://plantuml.com/json#1b6b8d6c715c3de9) for this.

**Comment by duncandewhurst** [comment]
I'm assuming that `temporal_resolution` under vulnerability is an error since that field only exists at the top level and as a property of `Resource`.

**Comment by matamadio** [comment]
> I'm assuming that `temporal_resolution` under vulnerability is an error since that field only exists at the top level and as a property of `Resource`.

Yes sorry, fixed.
