### ISSUE TITLE
[Schema] Temporal object / period

### ISSUE THREAD

**Issue by matamadio** [GFDRR/rdl-standard#179]
Looking to build an example for different reference time periods as in [fourth hazard example](https://github.com/GFDRR/rdl-standard/issues/135#issuecomment-1660109139).

- Set with current and future climate projected hazard data to show how temporal objects are used

  | Figure | Metadata |
  | --- | --- |
  | <img width="350" src="https://github.com/GFDRR/rdl-standard/assets/44863827/e64c32b2-6641-4b51-baf2-7b18717cbff1"> | <b>Title:</b> Aqueduct flood hazard maps<br><b>Description:</b> Probabilistic maps of coastal flood hazard occurrence frequency by return period.<br><b>Spatial extent:</b> Global<br><b>Risk Data type:</b> Hazard<br><b>Hazard type:</b> Coastal flood<br><b>Hazard processes:</b> Storm surge<br><b>Source model:</b> Aqueduct<br><b>Period(s):</b> <font color="#FF0000">2015, 2030, 2050, 2080</font><br><b>Analysis type:</b> Probabilistic<br><b>Frequency distribution:</b> Return periods<br><b>Occurrence range:</b> once in 5 to 1,000 years<br><b>Calculation method:</b> Simulated<br><b>Intensity measure:</b> Water depth [m]<br><b>License:</b> Open (CCY-BY) |

But is it actually possible to give an array of reference years withouth having to specify start and end year?

![immagine](https://github.com/GFDRR/rdl-standard/assets/44863827/8d95deb1-b5d7-4fa5-aca5-3651b9a95a32)

**Comment by matamadio** [comment]
No, they would be different resources. So an array of periods works fine.

The question more specifically is: should I fill the same start/end year whenever I just want to indicate the period with a single reference year for each resource (as oftern occurs with climate data)?

**Comment by odscjen** [comment]
Ah, sorry I misunderstood. Yes if you just want to indicate a single year then just put that year in as both `temporal.start` and `temporal.end`.

Also it won't be an array of periods, but an array of `resources` each of which will have a `temporal` object
