### ISSUE TITLE
[Schema] Commercial licenses?

### ISSUE THREAD

**Issue by matamadio** [GFDRR/rdl-standard#183]
How to attribute commercial licenses? (E.g. Fathom data).

Currently the list only includes open data licenses:
https://github.com/GFDRR/rdl-standard/blob/dev/codelists/open/license.csv

**Comment by duncandewhurst** [comment]
In the schema, license is an open codelist, so you can use values from outside the codelist. We'll need to update the spreadsheet template to allow the same.

**Comment by odscjen** [comment]
I'm closing this as the spreadsheet template now allows open values
