### ISSUE TITLE
[Schema] add generalized_extreme_values to frequency_distribution codelist

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdl-standard#186]
From suggestion in https://github.com/GFDRR/rdls-spreadsheet-template/issues/3#issuecomment-1671200463 add generalized_extreme_values to frequency_distribution.csv, a closed codelist

**Comment by odscjen** [comment]
@matamadio can you please provide a definition for the generalized_extreme_values code?

**Comment by odscjen** [comment]
actually don't worry, I've realised it's an easy one to look up for a fit to this codelist

**Comment by matamadio** [comment]
I would simly do as the other definitions:
"Data modelled using a generalized extreme value distribution".
