### ISSUE TITLE
[schema/documentation] Clarify the purpose of links

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdl-standard#187]
From suggestion in https://github.com/GFDRR/rdls-spreadsheet-template/issues/3#issuecomment-1671200463 create a codelist for `link.rel` from https://www.iana.org/assignments/link-relations/link-relations.xhtml. Currently this is just recommended in the field description

**Comment by duncandewhurst** [comment]
`links` only exists as a standards-compliant means of declaring the version of the RDLS schema that describes the data (using the 'describedby' code) so I don't think we need to include the IANA codelist in the standard. However, we should update the schema descriptions and documentation to clarify the purpose of `links`. Sound good?

**Comment by odscjen** [comment]
That makes a lot of sense to me, @matamadio is that sufficient?

**Comment by matamadio** [comment]
If the only IANA codelist expected is "describedby", then I don't see the reason to allow the choice to user. The field should have that value in the template already.

**Comment by duncandewhurst** [comment]
Sounds good. I've created an [issue](https://github.com/GFDRR/rdls-spreadsheet-template/issues/8) on the template repo and will rename this issue to be about clarifying the purpose of `links` in the schema and documentation.

**Comment by matamadio** [comment]
Agreed and implemented (auto-populating); this can be closed.

**Comment by odscjen** [comment]
I'm going to leave this open to remind us to include the clarification in the guidance as well as the autopopulation now in the spreadsheet
