### ISSUE TITLE
GEM exposure metadata to fit with data storage approach

### ISSUE THREAD

**Issue by matamadio** [GFDRR/rdl-standard#20]
The tables:

1. hazard.footprint_data
2. ged4all.cost, occupants and tags
3. loss.map_values
4. loss.curve_map_values

are meant to store data, consistently with the data-in-DB approach, and are substituted with link to S3 file in the current approach.
- 1 can be replaced with a link to file safely, as it only stores hazard value;
- 3 would store loss in relation to asset; in the most common case of vector or table ADM map with losses per unit that can be part of the file table itself, ane be removed from metadata attributes. 
- 4 is similar to 3, here we also have the "rates" field which is the specification associated to loss value (could be simply name of loss field in the table, eg rate_loss).

- **2 is problematic** because there are three tables that are meant to link to individual geometries in one exposure.asset (e.g vector buildings each with different cost, occupants and tags), like the "area" field of exposure.asset does; this is a peculiarity of exposure schema which makes it a bit trickier to untangle. Since providing a sum up of these tables for one dataset as metadata wouldn't provide much use (e.g total area of fotprints, total cost, total occupants..), my suggestion is to keep them all within the file data table, out-DB.
This is also one of the approaches proposed for taxonomy in GFDRR/rdl-standard#18

**Comment by stufraser1** [comment]
Reaplved by using JSON schema with latest changes
