### ISSUE TITLE
Specify the coordinate reference system to be used in the Location object

### ISSUE THREAD

**Issue by duncandewhurst** [GFDRR/rdl-standard#201]
The `Location` definition is based on the GeoJSON specification, [section 4 of which](https://datatracker.ietf.org/doc/html/rfc7946#section-4) states that:

> The coordinate reference system for all GeoJSON coordinates is a geographic coordinate reference system, using the World Geodetic System 1984 (WGS 84) [[WGS84](https://datatracker.ietf.org/doc/html/rfc7946#ref-WGS84)] datum, with longitude and latitude units of decimal degrees.  This is equivalent to the coordinate reference system identified by the Open Geospatial Consortium (OGC) URN urn:ogc:def:crs:OGC::CRS84.

We should state that explicitly in the descriptions of `.geometry.coordinates`, `.bbox` and `.centroid` so that implementers know which CRS to use and users/tools know how to interpret coordinates.

The alternative would be to allow publishers to use a CRS of their choosing and to add a field to disclose the CRS. However, I see two issues with that approach: the risk of confusion with `Resource.coordinate_system` and the need for systems that consume RDLS metadata to implement conversion between CRSs in order to render locations on a map.

**Comment by matamadio** [comment]
First option: use WGS84 for spatial reference attributes.
This remains independent from data epsg.

**Comment by odscjen** [comment]
I agree with the first option, just make is clear in the descriptions that WGS84 must be used along with decimal degrees.

@stufraser1 if you're also happy with this we can move this into the agreed and ready column
