### ISSUE TITLE
[Schema] url for a resource option and split into 2, one for access details and one for download

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdl-standard#209]
Currently the `resource.url` field is required and is designed to be a url that takes a user to the resource itself.

However there are instances where such a `.url` isn't available, e.g.
* the data hasn't been published yet
* the data is access restricted.

Therefore suggest that we remove `resource.url` and replace it with 2 optional fields:

`access_url` - a URL that gives access to the resource, e.g. a webpage through which a user can request access by completing a form.
`download_url` - The URL of the downloadable file in a given format.

@matamadio @stufraser1 how does this sound? This would help with the issue of commercial products such as Fathom and for internal only resources.

**Comment by matamadio** [comment]
Agree on the proposal. We have many cases for `access_url`
