### ISSUE TITLE
[Schema] Declare different schemes for disaster id

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdl-standard#221]
From a technical standpoint there is potential to reuse the new `Classification` object here. this would allow users to declare which scheme they're taking their disaster id from, e.g.:

```json

"disaster_identifer": {
  "id": "ak0238v9wqev",
  "scheme": "Shakemap ID",
  "description": "M 3.4 - 15 km ESE of Eagle River, Alaska"
  "uri": "https://earthquake.usgs.gov/data/shakemap/"
}
```

the scheme's that it's possible to use could be added to the `classification_scheme.csv` codelist which is open.

_Originally posted by @odscjen in https://github.com/GFDRR/rdl-standard/issues/142#issuecomment-1632592615_
          

This proposal would allow people to use other schemes other than GLIDE.

**Comment by odscjen** [comment]
As we'll need to add these schemes to the `classification_scheme` codelist other than GLIDE what are the common disaster schemes that you'd like to include? (This is an open codelist so we don't need to be exhaustive but it'd be good to include the ones you think users are most likely to reference)

**Comment by stufraser1** [comment]
- GLIDE; e.g., "EQ-2001-000033-IND"
- EM-DAT Dis No; e.g., "2014-0292-CHN"
- USGS PAGER event name; e.g., "M 3.7 - 44 km ENE of San Clemente Is. (SE tip), CA" or USGS PAGER event ID; e.g., "us7000krjx"
- DesInventar;new system online soon, cannot confirm format.

**Comment by odscjen** [comment]
> USGS PAGER event name; e.g., "M 3.7 - 44 km ENE of San Clemente Is. (SE tip), CA" or USGS PAGER event ID; e.g., "us7000krjx"

Looking into this PAGER is just one of the products produced by the USGS Earthquake Hazards Program, the other main one being ShakeMap. Both of these products use the same event ID. So I don't think it's appropriate to refer to it as the PAGER event ID. So I'm putting the scheme in as the "USGS Earthquake Hazard Program" and mentioning both PAGER and ShakeMap in the code description.

**Comment by odscjen** [comment]
> DesInventar;new system online soon, cannot confirm format.

From what I can see with this there aren't globally unique IDs for the disaster events covered by this tool. It looks as though there is a "datacard" for each country and event type and the identifier is only unique within each "datacard". Therefore I don't think we should include it. Once it's up and running properly it can be revisited.
