### ISSUE TITLE
[Website] Links, URLS and redirects

### ISSUE THREAD

**Issue by matamadio** [GFDRR/rdl-standard#226]
Before RDL dissemination, we need to update links and redirects.

In riskdatalibrary.org:

- [x]  Menu link "Data" should point to https://datacatalog.worldbank.org/search/collections/rdl (also rename it as "Collection"?)
- [ ]  Jkan to be euthanised 
- [x]  Redirect https://docs.riskdatalibrary.org/ should point to https://rdl-standard.readthedocs.io
- [x]  dev branch to be merged into latest 
- [x]  Create new redirect for http://rdsl-cove-dev-main.dokkurdlsdev1.ods.mobi/ , and add it to top menu, proposed url and names:
- [ ]  toolkit.riskdatalibrary.org
- [ ]  convertor.riskdatalibrary.org
- [ ]  this directs to cove tool while is the only tool done; it can become a landing page whenever we have more tools
- [ ]  I would add the link to standard GH repo directly on the top menu.

**Comment by duncandewhurst** [comment]
> * Redirect https://docs.riskdatalibrary.org/ should point to https://rdl-standard.readthedocs.io
>   
>   * dev branch to be merged into latest

Rather than setting up an HTTP redirect, we'll want to set https://docs.riskdatalibrary.org/ up as a custom domain per the instructions in https://docs.readthedocs.io/en/stable/guides/custom-domains.html#adding-a-custom-domain. This will involve updating the DNS settings for https://docs.riskdatalibrary.org/.

> Create new redirect for http://rdsl-cove-dev-main.dokkurdlsdev1.ods.mobi/ , and add it to top menu, proposed url and names:
> 
>     * toolkit.riskdatalibrary.org
> 
>     * metadata.riskdatalibrary.org
>       
>       * this directs to cove tool while is the only tool done; it can become a landing page whenever we have more tools

http://rdsl-cove-dev-main.dokkurdlsdev1.ods.mobi/ is the URL to the (temporary) development instance. I think that this will change once the live version is deployed. @radix0000 will need to let us know what the final URL is. As above, I think we'll want to configure the DNS records for the above subdomains, rather than setting up HTTP redirects or domain name forwarding.

**Comment by stufraser1** [comment]
> This will involve updating the DNS settings for https://docs.riskdatalibrary.org/.

Task for you, I think @pzwsk

**Comment by radix0000** [comment]
Have created the live server, though it isn't up and running yet.

I think our ideal would be for **toolkit.riskdatalibrary.org** and **metadata.riskdatalibrary.org** to each have a CNAME pointing at **rdls.cove.opendataservices.coop** (I have already created this subdomain).

This would give us some indirection/flexibility at our end as well.

**Comment by pzwsk** [comment]
Done

![image](https://github.com/GFDRR/rdl-standard/assets/2378439/0b6fbac9-861b-40c0-9bc7-18438e2e9cbd)

**Comment by pzwsk** [comment]
> I've added docs.riskdatalibrary.org as a custom domain in the Read the Docs admin portal. @pzwsk please can you do the next step:
> 
> > To configure this domain add a CNAME record in your DNS pointing your custom domain to `readthedocs.io`.

Done

![image](https://github.com/GFDRR/rdl-standard/assets/2378439/0b6fbac9-861b-40c0-9bc7-18438e2e9cbd)

**Comment by pzwsk** [comment]
Looks like there is an issue though.

![image](https://github.com/GFDRR/rdl-standard/assets/2378439/fe73b996-14d4-4d58-a5b0-101c415c0f90)

**Comment by duncandewhurst** [comment]
> Looks like there is an issue though.
> 
> ![image](https://user-images.githubusercontent.com/2378439/265064822-fe73b996-14d4-4d58-a5b0-101c415c0f90.png)

It should be working OK now. https://docs.riskdatalibrary.org and https://docs.riskdatalibrary.org/en/dev/ are working for me, and https://www.rdl-standard.readthedocs.io/ redirects to https://docs.riskdatalibrary.org. You might need to force a refresh (Ctrl+F5), clear your DNS cache or wait for DNS changes to propagate, but let me know if you're still having issues.

@radix0000 please could you look into the issue with rdls.cove.opendataservices.coop

**Comment by duncandewhurst** [comment]
> > https://www.rdl-standard.readthedocs.io/ redirects to https://docs.riskdatalibrary.org.
> 
> Both edge and firefox give me "unsafe connection" for https://www.rdl-standard.readthedocs.io, unsupported protocol.
> 
> `ERR_SSL_VERSION_OR_CIPHER_MISMATCH`

Oh, sorry. That's because I mistakenly typed `www.` at the start of the URL in my previous comment. The URL is actually https://rdl-standard.readthedocs.io/, which doesn't have those errors. There's no `www.` links 'in the wild' and I've edited my previous comment to remove it.
