### ISSUE TITLE
[Proposal] Clarify event and eventset properties in Hazard Data Package specification

### ISSUE THREAD

**Issue by ldodds** [GFDRR/rdl-standard#23]
## What is the context or reason for the change?

The current draft of the Hazard Data Package needs review by someone with more domain knowledge of Hazard data and the core conceptual model. There are several elements where clarifications are likely needed.

This issue lists the areas that need further review and revision.

## Why is this not covered by the existing model?

The properties are defined in the specification are based on the "MVP" data model and aim to align with the JKAN implementation. 

But additional documentation is needed to clarify how some of the properties might be used in practice. This might be case of improving or clarifying the documentation for the core model, with the Hazard Data Package specification then being revised to match.

## What is your proposed change?

The following areas need some review and likely rework. That work will require changes to both [the specification](https://github.com/GFDRR/rdl-standard/blob/main/specs/hazard-data-package/spec.md) and [the JSON schema](https://github.com/GFDRR/rdl-standard/blob/main/specs/hazard-data-package/schema.json):

* The Event Set descriptor briefly describes the `start_date`, `end_date`, `time_span` and `year` properties, but doesn't say how and when they are used together. I believe the intention may be that an Event Set will either have a start/end date and a time span OR a year. And not all four. It's also not clear if the `time_span` is `REQUIRED` if you also have the start/end dates?
* The Event Set descriptor notes that it may have a `spatial` coverage. But won't this always be the same as the `spatial` property for the package?
* Should the Event Descriptor have a `frequency` property or is it `frequency_type`? Different versions of the schema use different names
* For an Event Descriptor how will the `frequency`, `return_period` and `occurence` properties be used together? Are these used together?

**Comment by matamadio** [comment]
Premise: time span is only relevant for empirical models describing real events (inferred or observed).

Answering Leigh points:

> The Event Set descriptor briefly describes the start_date, end_date, time_span and year properties, but doesn't say how and when they are used together. I believe the intention may be that an Event Set will either have a start/end date and a time span OR a year. And not all four. It's also not clear if the time_span is REQUIRED if you also have the start/end dates?

- Start and End date are required for real events. Timespan is optional (can be obtained from End - Start)
- Year is for more generic time reference

Examples:
- ASI drought index (Start date: 1984; End date: 2021; Timespan: 38 years)
- Flood extent from satellite observations for Nigeria floods (Start date: May 2022; End date: November 2022)
- Air pollution layer for 2022 (Year: 2022).

> The Event Set descriptor notes that it may have a spatial coverage. But won't this always be the same as the spatial property for the package?

That is correct, however the individual hazard layers may have more specific locations. For example package might be about "India" but then inside there is one hazard layer for Calcutta, one for Dheli, etc.
That is not critical to report on metadata, but might be good to have. What do you think @stufraser1 ?
For now, I suggest to keep only the resource spatial properties.

> Should the Event Descriptor have a frequency property or is it frequency_type? Different versions of the schema use different names

There is now only one main frequency attribute: frequency_type (applies to H and thus linked into V and L).

> For an Event Descriptor how will the frequency, return_period and occurence properties be used together? Are these used together?

We now have Frequency_type as mandatory field for HZD, occurrence has been removed/merged.
I propose a child attribute if Return Period is selected, to specify the range of scenarios e.g. RP 10 to 1000 years.
![immagine](https://user-images.githubusercontent.com/44863827/214564142-1fc4ff13-8783-42c8-9cc6-a6c85904ad9c.png)

**Comment by matamadio** [comment]
Superceeded by #59
