### ISSUE TITLE
[Proposal] Improve Hazard Data Package JSON Schema

### ISSUE THREAD

**Issue by ldodds** [GFDRR/rdl-standard#24]
## What is the context or reason for the change?

A [simple JSON Schema](https://github.com/GFDRR/rdl-standard/blob/main/specs/hazard-data-package/schema.json) has been created for the draft Hazard Data Package. It should be maintained alongside the human-readable specification.

Using JSON Schema makes it easy to create validators to check whether a data package has the right structure. [There are many implementations](https://json-schema.org/implementations.html), including some [online versions](https://json-schema.hyperjump.io/)).

There is also [an official JSON schema](https://specs.frictionlessdata.io/schemas/data-package.json) for the core data package specification. This was used as the basic for the example, but was stripped back to create a minimum working version. 

(That schema also doesn't use the latest version of the JSON schema specification.)

## Why is this not covered by the existing model?

The JSON schema is just a draft to demonstrate the value of having a validator. It's not yet complete, but maintaining it will improve the specifications.

## What is your proposed change?

There are a few things to improve:

* The current version only has the properties that are documented in the specification. But there are other valid properties of a data package that could be added, e.g. `created`, `contributors`, `keywords`. Definitions of those could be copied over to enrich the schema
* Improve the constraints for the individual properties. Some properties already have patterns and formats defined. But these might be applied elsewhere, e.g. for fields which conform to a regex pattern, like [country codes](https://github.com/frictionlessdata/schemas/blob/master/definitions.json#L209)
* There are some repeated properties, e.g. `id`, `title`, etc. It might be better to define these as reusable schema fragments and import them. See [the example here](https://json-schema.org/learn/getting-started-step-by-step.html#references-outside-the-schema). This will also make it easier to create schemas for other parts of the data model (e.g. for Exposure, Loss, etc)
* Related to this, the code lists could be turned into JSON schema fragments that define `enum` values for all legal values. That would allow properties like `hazard_type` to be validated against the actual list

**Comment by stufraser1** [comment]
Currently, the spatial object is given in the eventset object and the data package level.  Whilst a single eventset is allowed in the package, this is an unnecessary duplication. It becomes useful if >1 eventset could be included, as an eventset may then cover a subset of the spatial coverage of the data package
