### ISSUE TITLE
[DATA] MHRA INDIA (RMSI data)

### ISSUE THREAD

**Issue by matamadio** [GFDRR/rdl-standard#40]
## Dataset overview

Dataset produced for INDIA by RMSI consultant along previous MHRA project (now decomissioned geoportal).
![immagine](https://user-images.githubusercontent.com/44863827/231196331-38d4a881-544a-4e94-8b0a-528e4b7f81c8.png)
Data were paid again to be released by S. Hallegatte (USD 15k). Time to save these long-term on RDL collection.
Data cover several hazards for India.

## Dataset details and structure

The shared output is made of hazard layers, each one represening a specific hazard magnitude in relation to its probability (Return Periods).

### Hazards included

- **River flood**: 100 m probabilistic model by RMSI, complemented by 1 km global model. Data as grid shapefiles for each state.  Return periods: 2, 5, 10, 25, 50, 100 years. Size: 1.8 Gb.
![immagine](https://user-images.githubusercontent.com/44863827/231192422-716c41f9-dbe6-4b03-a999-44c41261227c.png)

- **Storm surge**: two datasets from probabilistic modelling:
  - 100 m country-level raster representing water depth.  Size: 260 Mb.
  - 1 km state-level grid shapefiles including both water depth and velocity variables. Size: 2.55 Gb.
Return periods: 2, 5, 10, 25, 50, 100, 250, 500, 1000 years.
![immagine](https://user-images.githubusercontent.com/44863827/231192244-2d7ea761-5633-41ae-a7d4-7daa4034586b.png)

- **Cyclone flood**: 100 m probabilistic model by RMSI, complemented by 1 km global model. Data as grid shapefiles for each state.  Return periods: 2, 5, 10, 25, 50, 100, 250, 500, 1000 years. Size: 5.7 Gb.
![immagine](https://user-images.githubusercontent.com/44863827/231194717-59bd5c96-01dc-4d44-90d4-db3bff4114c8.png)
The high-resolution model (100m) is applied over urban areas:
![immagine](https://user-images.githubusercontent.com/44863827/231226589-29e995eb-2f05-45de-b57b-27e8dcd44ae1.png)

- **Cyclone wind**: 10 km probabilistic model by RMSI. Country-wide raster data as a merge of state-level simulations).
Return periods: 2, 5, 10, 25, 50, 100, 250, 500, 1000 years. Size: 3 Mb.
Shapefile data are also provided, size is 25 Gb - to be downloaded and reviewed
![immagine](https://user-images.githubusercontent.com/44863827/231193058-a5fc02dd-0a2c-40e9-b338-f1dc82ddec91.png)

- **Tsunami**: two country-level raster datasets:
  - 100 m probabilistic (RP 500 years)
  - deterministic (east India)
 Size: 50 Mb.
![immagine](https://user-images.githubusercontent.com/44863827/231196792-424b2a13-b08f-4211-920d-a4416071f4d4.png)

- **Wildfires**: 25 m raster grid susceptibility model for two states: Jammu & Kashmir. Size: 10 Mb.
![immagine](https://user-images.githubusercontent.com/44863827/231197831-1f2da1a1-7f68-45f1-a595-bcf77af2c0ba.png)

- **Drought**: 16 Gb of data uploaded on April 17; to be downloaded

**Comment by matamadio** [comment]
In terms of data efficiency, we could easily reduce the size of both fluvial and cyclone flood layers by turning the polygon grids (only the high-resolution sections) into deflated raster grids of the same resolution. The polygon grids only carry one value, as such there will be no loss of information.

**Comment by matamadio** [comment]
# Exposure data

The largest share of data - about 110 Gb split into ADM1 (state) folders by ISO_a2 code. There are 34 states folders.

Folders structure:
```
- ISO_a2
  - Line
  - Point
  - Polygon
  - Raster
```
Each folder contains different exposure components:

### Line
The largest folder in terms of size. Includes `shapefiles (line)` representing the transport network (roads, bridges, railways and subways), transmission lines and embankments.

### Point
Includes `shapefiles (point)` representing public places and infrastructure locations by category, such as health facilities, cyclone shelters, dams, schools, fire stations, and more.

### Polygon
Includes `shapefiles (polygon)` representing the area of key structures and infrastructures such as power plants, sea ports, refineries, but also slums and mangroves extent.

These vector datasets have been derived from Open Street Map and national sources; for some of them, additional attributes have been added in the shapefile database, in particular the key attributes are **replacement value** and building features (n. of storeys, structure type, construction year) which can be used for risk analytics. _**Note that for many layers, these attributes are empty of values.**_

All these olders should be individually zipped for size efficiency (about 10% of original size).

### Raster
Includes one large tif files showing agricultural area (tblagricultureexposure_`ISO_a2`.tif); some states also have (tbllulcexposure_`ISO_a2`.tif) showing land cover types (LULC). The two datasets are not aligned.
The raster data are not compressed; this should be done before storage for efficiency.

tblagricultureexposure_wb.tif
- Original size: **400 Mb**
- Compressed size: **6.3 Mb**

## METADATA

**METADATA folder:** Comprises of two types of metadata, namely Hazard and Exposure. Excels and pdf file is available for all the hazards and exposures captured in IMHRA study. Additionally, a readme (MS EXCEL) is available with:
- State Codes
- Exposure layers covered with state wise layer name for each exposure
- Detailed hazard layers present with table name and return periods covered.

**Comment by matamadio** [comment]
# Workflow to package and store exposure data

- Download data and metadata from the [RMSI sharepoint](https://rmsiindia-my.sharepoint.com.mcas.ms/personal/lokendra_dixit_rmsi_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Flokendra%5Fdixit%5Frmsi%5Fcom%2FDocuments%2FI%5FMHRADATA%5FRMSITOBANK&ga=1).
- Compress raster data (use GDAL batch) in `Raster` folders
- Zip shapefile folders (`Line`, `Point`, `Polygon`)
- Metadata: either provide one zip with all the metadata as resources; or copy the metadata in each state folder (_let's decide one or the other_)
- Upload the data in the DDH folder on sharepoint

This is the first step to secure data; then we need to produce appropriate metadata files for each one to be included in the WB data catalog.

- Create an excel spreadsheet describing the datatype with each dataset name, URL to data and URL to prepared JSON metadata.
- Describe the data structure to be achieved on DDH.

DDH team will then copy the data and metadata to DDH Sharepoint; the datasets will appear in your `My Datasets` for review and any further editing.

### Split the effort!
34 folders processed by x consultants (Mat, Bramka, Asmita) = 11 folders each

**Comment by bramkaarga** [comment]
Upload by **Bramka**:
- Hazard datasets: Drought
- Exposure datasets:  AR, BR, CN, GH, HP, HR, JH, KA, MH, ML, MN, MP, MZ.
