### ISSUE TITLE
[Docs update] Restructuring the docs

### ISSUE THREAD

**Issue by matamadio** [GFDRR/rdl-standard#43]
New documentation structure following the guidance in the [ODS review](https://docs.google.com/document/d/1dBK7dr7JzHnLwcR9RTHybjpaS8JViopu5LLGPHqpm2c/).

**[SEE ONLINE PREVIEW](https://rdl-standard.readthedocs.io/en/docs.mat/)**

Section | Mode | Description of Content | RDLS existing content | Additional content
-- | -- | -- | -- | --
Primer (first page) | Explanation | Introduction to the domain, key concepts and reasons for standardising data, description of how the standard was developed and why, who the intended users are | Introduction, Taxonomies (but link to definition of RDLS Hazard taxonomy in other section), paragraphs in Data model pages discussion why certain attributes are included | Core standards, History
Schema reference | Reference | The schemas, codelists and rules that need to be followed to publish data | Data model attribute tables and examples, RDLS Hazard taxonomy |  
Guidance | How-to guides | step by step guides to implementing the data standard. | Implementation |  
Glossary |   |   | Key concepts |  
Support | How-to guides |   |   | support details

More in detail, navigation bar (sections) proposal:

- Primer (first page)
  - Core standards 
  - History
- RDL schema
  - Overview
  - Hazard
  - Exposure
  - Vulnerability
  - Loss
- Guidance
  - Data preparation
    - Data formats 
- Glossary
  - Risk definitions
- Support
  - External resources
  - Contacts

**Comment by stufraser1** [comment]
Reviewing:
Small edits committed directly on docs.mat branch.
Larger edits created on docs.mat.stu-? branches and PR created for @matamadio review

**Comment by stufraser1** [comment]
To do:

- [ ] Data_model > hazard to be updated from new JSON schema
- [ ] Data_model > exposure to be updated from new JSON schema
- [ ] Data_model > vulnerability to be updated from new JSON schema
- [ ] Data_model > loss to be updated from new JSON schema
- [ ] Data_model class diagram to be updated as field names change in new JSON schema

**Comment by stufraser1** [comment]
GLIDE added at https://rdl-standard.readthedocs.io/en/dev/rdl/core-standards.html#hazard-data-standards

**Comment by duncandewhurst** [comment]
> To be updated from new JSON schema
> - [ ] Data_model > hazard 
> - [ ] Data_model > exposure 
> - [ ] Data_model > vulnerability
> - [ ] Data_model > loss 

https://github.com/GFDRR/rdl-standard/pull/120 updates the reference documentation (formerly known as the data model section). The schema tables are now generated from the schema as part of the Sphinx build so they will always be up-to-date and `manage.py` includes a pre-commit script to update the sub-schema and codelist reference sections.

The diagrams, explanatory text and examples will need updating once the schema updates are done.

**Comment by duncandewhurst** [comment]
From https://github.com/GFDRR/rdl-standard/pull/120#pullrequestreview-1514353674:

> We also need to update the examples for each section to make a range of examples available with the JSON implementation of the metadata rather than tabulated values. This could include snippet of JSON in the documentation, or a link out to the metadata file if larger.

**Comment by matamadio** [comment]
Suggest to make longer tables (such as in codelists) collapsible, or other way to make the page more readable.

**Comment by duncandewhurst** [comment]
@stufraser1 @matamadio building on the work in this issue and the proposed updates to the landing page in https://github.com/GFDRR/rdl-standard/pull/170/, I've been thinking about the structure and framing of the documentation and have the following proposal on which I would like your feedback. Implementing this is mostly a case of renaming/reorganising existing content, although there a couple of new pages to author.

The objectives of the proposed updates to the structure and landing page content are: to clearly differentiate the concepts of metadata and risk datasets and to explain the role of RDLS in relation to those concepts; to provide a clear introduction to RDLS for new readers; and to provide make it easier for returning readers and implementers to find the information that they need.

## Structure

Section | Content 
-- | --
**Introduction** |
-- What is the RDLS? | New content: A high-level description of the scope and content of the standard, including a summary of structure of the metadata standard (datasets, resources, hazard metadata, exposure metadata, vulnerability metadata, loss metadata) and the role of the schema and codelists
-- Why use the RDLS? | Existing content from [use cases page](https://rdl-standard.readthedocs.io/en/dev/rdl/use-cases/)
-- How do I implement the RDLS? | New content: A high-level summary of how to implement RLDS (publish metadata according to the schema, follow guidance on packaging and formatting risk datasets) and supporting tools (spreadsheet template, conversion and validation tool)
-- How does RDLS relate to existing standards | Existing content from [core standards page](https://rdl-standard.readthedocs.io/en/dev/rdl/core-standards/) and integrate content from [taxonomies page](https://rdl-standard.readthedocs.io/en/dev/taxonomies/) about 3rd party taxonomies
**Metadata reference** |
-- Schema reference | Existing content from [schema reference page](https://rdl-standard.readthedocs.io/en/dev/reference/schema/)
-- Schema browser | Existing content from [schema browser page](https://rdl-standard.readthedocs.io/en/dev/reference/browser/)
-- Codelists | Existing content from [codelist reference page](https://rdl-standard.readthedocs.io/en/dev/reference/codelists/) and integrate content from taxonomies about RDLS taxonomies
**Guidance** |
-- How to publish RDLS metadata | New content, building on [RDL metadata page](https://rdl-standard.readthedocs.io/en/dev/guides/rdl-metadata/)
-- How to publish risk datasets |
---- How to package risk datasets | Existing content from [data packaging page](https://rdl-standard.readthedocs.io/en/dev/guides/preparation/#data-packaging)]
---- How to format risk datasets | Existing content from [data formats page](https://rdl-standard.readthedocs.io/en/dev/guides/formats/)
**Glossary** | Existing content from [glossary of terms page](https://rdl-standard.readthedocs.io/en/dev/glossary/)
**About**
-- Contacts | Existing cnotent from [contacts page](https://rdl-standard.readthedocs.io/en/dev/about/contacts/)
-- Changelog | Existing content from [changelog page](https://rdl-standard.readthedocs.io/en/dev/about/changelog/)
-- Governance | Existing content from [governance page](https://rdl-standard.readthedocs.io/en/dev/about/governance/)
-- License | Existing content from [license page](https://rdl-standard.readthedocs.io/en/dev/about/license/)
-- History and roadmap | Existing content from [history and roadmap page](https://rdl-standard.readthedocs.io/en/dev/rdl/roadmap/)

## Landing page content

> The Risk Data Library Standard (RDLS) is an **open metadata standard** for describing risk datasets used in climate and disaster risk assessments. 
> 
> The purpose of the RDLS is to enable risk reduction and resilience building by making it easier for risk data publishers to describe their datasets and for risk data users to identify datasets to use in their work. Many different organisations produce or use risk datasets, including humanitarian organisations, insurance companies, academic institutions and multi-lateral development banks.
> 
> The key feature of the RDLS is the metadata standard for describing **hazard**, **exposure**, **vulnerability**, and **loss** datasets. Whilst the RDLS does not seek to standardise risk datasets themselves, in addition to the metadata standard, it provides guidance on packaging and formatting for risk datasets.
> 
> The RDLS is curated by the [Global Facility for Disaster Reduction and Recovery](https://www.gfdrr.org) and is intended for use by anyone involved in publishing or using disaster risk data. It is an open standard and community contributions are welcome.
> 
> The standard originated from in-depth consultations with the disaster and climate risk modeling community on improving access to risk datasets. It is the result of the collective effort and ongoing support of internationally-recognised research institutions and established global partnerships, bring together expertise in multiple hazards and all aspects of risk assessment. 
> 
> To help you use RDLS effectively, the documentation includes the following sections:
> 
> * An [introduction]() to the RDLS
> * [Reference]() documentation for the metadata standard
> * [Guidance]() on how to publish metadata in RDLS format and how to package and format risk datasets
> * A [glossary]() of risk terminology
> * Background information [about]() the RDLS, including how it is governed, its history and roadmap, and who to contact for more information

**Comment by stufraser1** [comment]
I think this is a lot clearer than the current landing page, From my perspective, please go ahead. @matamadio ?

**Comment by matamadio** [comment]
Yes, I like it. Please do.

**Comment by odscjen** [comment]
closing this as it's been addressed in #175
