### ISSUE TITLE
Updating the JSON Schema 

### ISSUE THREAD

**Issue by odscrachel** [GFDRR/rdl-standard#45]
Issue to track changes to the JSON schema. 
Some of the changes needed are listed below, this is not comprehensive. I'll open a new PR with the changes we have made already. 

- [x] in `anyOf.vulnerability.model.approach` change reference #/definitions/f_subtype to #/definitions/vulnerability_f_subtype
- [x] add #/definitions/vulnerability_f_relationship
- [x] add #/definitions/vulnerability_f_math 
- [x] Change definitions to $defs to allow it to validate (this may change depending on version)
- [x] Removed the following fields which are not metadata
       `anyOf.exposure.model.occupancy`
       `anyOf.exposure.model.occupancy_time`
       `anyOf.exposure.model.taxonomy_code`
       `anyOf.exposure.model_add_attributes`
       `anyOf.vulnerability.model.taxonomy_code`
       `anyOf.vulnerability.specifics.par_names`
       `anyOf.vulnerability.specifics.im_name`
       `anyOf.vulnerability.specifics.im_units`
       `anyOf.vulnerability.specifics.n_events`
       `anyOf.vulnerability.specifics.n_assets`
       `anyOf.vulnerability.specifics.is_fit_good`
       `anyOf.vulnerability.specifics.is_edp_thre`
       `anyOf.vulnerability.specifics.is_dm_factor`
       `anyOf.vulnerability.specifics.is_casualties`
       `anyOf.vulnerability.specifics.is_downtime`
- [x] Remove `common.contribution` nesting
- [x] Move `common.contribution.required` to `common`
- [ ] Update all field names and descriptions inline with the changes [discussed here](https://docs.google.com/spreadsheets/d/1zJjNjiZBf5Tk06NnYkBMJxC0d9Q1QfEhla4N57jGc2U/edit#gid=740149783).
- [ ] Update required fields for all objects
- [ ] Update `anyOf` to `oneOf`
- [ ] Create CSV codelists 
- [ ] Update other nesting 
- [ ] Expand definitions
- [ ] Add identifiers where needed 
- [ ] Once final version of JSON has been agreed, check it validates

**Comment by odscjen** [comment]
closing as superceded by more specific issues
