### ISSUE TITLE
[Proposal] License

### ISSUE THREAD

**Issue by odscrachel** [GFDRR/rdl-standard#55]
## What is the context or reason for the change?

There is an issue that a free text `licence` field could result in people mistyping the licence name or just using slightly different versions of the name, e.g. CC - BY - SA - 4.0 or CC-BY-SA-4.0 which would be read as different by a machine.

## What is your proposed change?

Consider creating a codelist to address this issue. 

## Why is this not covered by the existing model?

The current model has a `license_code` field (Type of license) which is free text.

**Comment by duncandewhurst** [comment]
We should check this proposal against DCAT's guidance on [License and rights statements](https://www.w3.org/TR/vocab-dcat/#license-rights). It recommends using canonical URIs of well-known licenses.

**Comment by stufraser1** [comment]
Licence codelist should include open and commercial licences.
