### ISSUE TITLE
[Proposal] Reframing of Loss schema: different output types, link to "RISK" concept

### ISSUE THREAD

**Issue by matamadio** [GFDRR/rdl-standard#6]
There are at least 4 types of loss data that could be part of a risk assessment, according to the [key concepts we reference](https://gfdrr.github.io/rdl-docs/keyconcepts.html):

1. **Simulated Impact/loss**: cost for one event/occurrance probability (eg RP100 event impact loss). Expressed as USD or damage%.
2. **Modelled Risk**: combination of lossess and probabilities into AAL or other metric (eg AAL for floods RP10-1000). Usually expressed as USD or damage%.
3. **Exposed asset**: subset of exposure amount falling within hazard extent, no vulnerability function available/applied (eg all population falling within RP100 considered "at risk"). The result is an [exposure x hazard map](https://disasterrisk.af/layers/geonode:landslide_hazard_exposure_pop_admin1), which can be expressed in m2, n, USD, others.
4. **Empirical losses**: observed losses caused by historical events (eg point losses for event 12/02/2015). Can be expressed as USD, list of impacted elements or damages, damage%.

Currently the Loss schema is meant to hold only simulated loss scenarios (1) and modelled risk (2), although there is no formal distinction between the two: eg a loss dataset can include individual loss scenarios (RPn), and combined risk estimation (AAL).

Loss RP10 | Loss RP50 | Loss RP100 | AAL
-- | -- | -- | --
10 | 30 | 50 | 15

### Proposals:

- Schema may be renamed with a more comprehensive-representative name ("RISK"). I think it is expected to find "risk" in the "risk data library".
- We may want to include an additional attribute in the schema to distinct Individual scenarios (1) and aggregated estimation (2).
- Total asset at risk (no risk modelling) may be part of asset schema, or part of loss schema flagged with a new attribute.
-  In some cases, empirical losses represent the data on which risk estimates are validated, and as such they have a core relevance for modelling. The loss schema can include the "calculation method" attribute (Inferred; Simulated; Observed) as in https://github.com/GFDRR/rdl-standard/issues/30#. "Observed" could be used to include empirical losses events, similarly to how it is used in H schema for empirical hazard events. I can't see a strong argument against this.

**Comment by matamadio** [comment]
Reframed issue and moved to rdl-standard for discussion.

**Comment by stufraser1** [comment]
superceded by discussion / updates in new schema

**Comment by matamadio** [comment]
From JRC-DRKMC, early adopters of the RDLS:

> As noted in my previous email, we would appreciate additional clarification on how risk is currently being captured by the RDL. At present, risk data appears to be classified under the “Loss” category. From our perspective, this approach may be potentially misleading for some users.
> 
> For this reason, we have, for the time being, taken the liberty  to adjust the RDLS spreadsheet ([https://github.com/GFDRR/rdls-spreadsheet-template](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGFDRR%2Frdls-spreadsheet-template&data=05%7C02%7Cmamadio%40worldbank.org%7C1fa01c5e140d4478143408de53792f65%7C31a2fec0266b4c67b56e2796d8f59c36%7C0%7C0%7C639039977172119837%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=THFcYW5xtj1v87Vl5%2BxAQcsuoV7Mysmta86KJhqBSMQ%3D&reserved=0)) by introducing a dedicated sheet for risk
> 
> <img width="1916" height="246" alt="Image" src="https://github.com/user-attachments/assets/017c7f2b-3966-4a65-8e71-8439834be18a" />

Although I think the current naming framework makes good sense ("loss" covering both recorded disaster data and probabilistic risk), the fact that our first adopter already feels the need to override suggests we might be missing the objective.

@duncandewhurst @stufraser1 this decision is functional to release v1.0

**Comment by duncandewhurst** [comment]
If the attributes required to describe actual loss data and probabilistic loss data are the same I think it makes sense to group them together in the schema, but I can see that there might be some confusion between 'risk data' as an overall term for hazard, exposure, vulnerability and loss data, and 'risk data' as a description of the output of a cat model.

Is there an alternative term to 'loss' that better communicates that the category can contain both datasets describing actual losses and datasets describing likely (probabilistic) losses? Would 'impact' work?

Whatever name is chosen, if the grouping of actual and probabilistic data under the same category is likely to cause confusion, it should be explained clearly on the ['What is the RDLS?' page](https://docs.riskdatalibrary.org/en/latest/rdl/what/) and in the code description in the [risk_data_type](https://docs.riskdatalibrary.org/en/latest/reference/codelists/#risk-data-type) codelist. Reading as a non-expert in the domain, neither the page nor the description of the 'loss' code clearly states that is the case.

**Comment by matamadio** [comment]
Thanks Duncan, I agree on this point:

> confusion between 'risk data' as an overall term for hazard, exposure, vulnerability and loss data, and 'risk data' as a description of the output of a cat model.

Each of the 4 components is "risk data":
- "risk" being defined as "Probability of losses"
- losses being calculated from impact > which is calculated as H x E x V
- probability of impact defined by the probabilistic model (usually H)

> Would 'impact' work?

I don't think so,
- impact already being a sub-component of losses
- wouldn't better comply with user request to have a category named "Risk"

-------------------

Ultimately the 2 options we have:
### 1. Defend current naming
- Explain more clearly the logic behind our choice in docs, supported by studies and partners review
- Revise fields description in loss component to explain "risk as probability of losses"
- Add some guidance text in the editor for each component tab:
  <img width="80%" src="https://github.com/user-attachments/assets/86cb189d-7e04-4b4e-b042-38ef4442d45c" />

JRC might still prefer to add their custom "risk" component.

### 2. Propose renaming to steering committe
- This change would need to be discussed by SC, as it has major implications all across the RDL.
- If to be applied to v1.0 release, needs to be addressed asap

My preference is for **1 - Defend current choice**.

@pzwsk @stufraser1 @bennyistanto

**Comment by stufraser1** [comment]
I'm tempted to say +1 to defend current choice and add more description where needed. 

Changing 'Loss' to 'Risk' as the component name is not a solution that resolves all potential misunderstanding / makes exactly clear the contents on its own. **I do not think there is a single word that would achieve complete clarity. 'Risk metrics' could work, if we can use two words.**

Positives of using 'Risk':
- may work better for the framing of including e.g., exposed assets or affected people, and none monetary effects. 
- may reduce some questions about whether we include 'damage' as referred to in the 'loss and damage' debate

Negatives of using 'Risk': 
- Risk estimates are also known by some as 'loss estimates', so do we just reverse the problem?
- 'Risk' is also an umbrella term - hence its use in the title 'Risk Data Library'. 
- 'Risk' could be interpreted by some as precluding scenario loss estimates or estimates of impact, which refer to impact from one event. It will be interesting to understand whether JRC need to include scenario loss data and whether they deem renaming it as 'Risk' data is workable for that case.

Using 'Impact' could be seen as even more specific, being a term used to describe the effect of a single event scenario, so is even less representative of including return period loss estimates. 

Documentation states: 'The loss component provides metadata describing data generated in risk assessments, i.e., modelled impacts and losses for single historical events or hypothetical scenarios and risk estimates from analysis of large event sets.' - which covers the range of metrics it is intended for, but perhaps we can make this clearer.

**Comment by pzwsk** [comment]
If we want Loss to be used for both modeled and historical losses, then it
should not be renamed as Risk as an historical loss is not a risk.

I think that is the decision point to me.

Best,
Pierre

**Comment by stufraser1** [comment]
Decision from team discussion above, and lack of 100% clarity that renaming to another single word offers, we have decided to continue with the naming 'Loss' and improve the description of what the component contains, in the MDE and documentation.

Tasks: 
- [ ] update docs
- [ ] update MDE

**Comment by matamadio** [comment]
> we have decided to continue with the naming 'Loss' and improve the description of what the component contains, in the MDE and documentation.

Also in the description of the field and examples within the schema.

**Comment by stufraser1** [comment]
A further question on this raised by a steering group member: Is it possible to more clearly flag the type of loss data in the loss component. Currently we rely on `analysis_type`, which we conclude it is not enough, so we should include a new object with new codelist referencing: https://github.com/GFDRR/rdl-standard/issues/6#issue-861100273.

`loss.type` ([codelist](https://docs.riskdatalibrary.org/en/latest/reference/codelists/#loss-type)) is already taken; I would prefer we use l`loss.type` and propose changing current`loss.type` to `loss.perspective` which is a common name for that group of terms in the insurance industry.

Proposed codelist:

Code | Title | Definition
-- | -- | --
historical | Historical Loss | Observed/reported losses caused by historical (previous) events, for example derived from a historical loss catalog.
exposed | Exposed Value | Subset of total exposure located within the extent of an event footprint. No vulnerability function is applied so the result is a measure of how many assets/people or the value of assets that are considered affected or "at risk".
scenario | Scenario Loss | Loss or impacts simulated for event scenario(s) such as a hypothetical 'worst-case' or historical events.
risk | Risk Estimates | Combination of loss estimate and associated probability/frequency, i.e. AAL or return period loss estimates.

- [ ] create codelist 
- [ ] update schema enums
- [ ] add to docs

**Comment by stufraser1** [comment]
Review please @duncandewhurst @matamadio

**Comment by matamadio** [comment]
> `loss.type` ([codelist](https://docs.riskdatalibrary.org/en/latest/reference/codelists/#loss-type)) is already taken; I would prefer we use l`loss.type` and propose changing current`loss.type` to `loss.perspective` which is a common name for that group of terms in the insurance industry.
> 
> Proposed codelist:
> Code | Title | Definition
> -- | -- | --
> historical | Historical Loss | Observed/reported losses caused by historical (previous) events, for example derived from a historical loss catalog.
> exposed | Exposed Value | Subset of total exposure located within the extent of an event footprint. No vulnerability function is applied so the result is a measure of how many assets/people or the value of assets that are considered affected or "at risk".
> scenario | Scenario Loss | Loss or impacts simulated for event scenario(s) such as a hypothetical 'worst-case' or historical events.
> risk | Risk Estimates | Combination of loss estimate and associated probability/frequency, i.e. AAL or return period loss estimates.

While understanding the drive, aside from having one option named "risk" in a dropdown, I don't see this helping on clarity; the proposed codelist has non-mutually exclusive options that could lead to ambiguous interpretation, i.e.
- `historical` does not exclude to have measures of just `exposed value`
- `risk` is usually tied to a `scenario` - which could refer to an `historical` period as well as future

My preference would be to add explanations and guidance instead of new fields as the whole "loss" object can be interpreted as "risk". But I'll have some more thinking on alternative logic and approach.

**Comment by samroeslin** [comment]
Beyond the naming issue, the primary concern is the absence of clear guidance on how disaster risk information should be encoded (where “[disaster risk](https://www.preventionweb.net/understanding-disaster-risk/component-risk/disaster-risk)” is understood as the computational output resulting from the interaction of hazard, exposure, and vulnerability).

The loss metadata has mandatory fields: 
- `hazard type`
- `asset category` ([exposure_category](https://docs.riskdatalibrary.org/en/latest/reference/codelists/#exposure-category))
- `asset dimension` ([metric_dimension](https://docs.riskdatalibrary.org/en/latest/reference/codelists/#metric-dimension))
- `impact type` [(impact_type)](https://docs.riskdatalibrary.org/en/latest/reference/codelists/#impact-type)
- `impact modelling` [data_calculation_type](https://docs.riskdatalibrary.org/en/latest/reference/codelists/#data-calculation-type)
- `impact metric` [impact_metric](https://docs.riskdatalibrary.org/en/latest/reference/codelists/#impact-metric)
- `quantity kind` [quantity_kind](https://docs.riskdatalibrary.org/en/latest/reference/codelists/#quantity-kind)
- `loss type` [loss_type](https://docs.riskdatalibrary.org/en/latest/reference/codelists/#loss-type)
- `loss approach` [function_approach](https://docs.riskdatalibrary.org/en/latest/reference/codelists/#function-approach)
- `loss frequency type` [analysis_type](https://docs.riskdatalibrary.org/en/latest/reference/codelists/#analysis-type)

------------------------------------------------------------------------------------------------------------------------
The current challenges of expressing disaster risk using the current RDLS loss schema is explained using the example of **[probabilistic river flood risk](https://drmkc.jrc.ec.europa.eu/risk-data-hub#/atlas/metadata/risk_river_flood) for Europe**

- `hazard type`
The hazard type codelist is missing in the RDLS Metadata Editor. The documentation list hazard taxonomies (see https://docs.riskdatalibrary.org/en/latest/rdl/other-standards/) but it is not clear which one is used in the RDLS Metadata Editor
- `hazard process`
This is a non-mandatory field nevertheless if "Flood" was selected for "hazard type" the field "Hazard process" doesn't allow for the selection of "river flood"

Suggestion
- [ ] Offer the user the option to select the hazard taxonomy (i.e. [UNDRR 2025 Hazard Information Profiles (HIPs)](https://www.preventionweb.net/drr-glossary/hips), [EM-DAT Disaster Classification System](https://doc.emdat.be/docs/data-structure-and-content/disaster-classification-system/)) before filling the "Hazard type" and "Hazard process". Once the user selected a specific hazard taxonomy, the RDLS Metadata Editor should reflect the corresponding hazard taxonomy with the corresponding hazard code/identifier

**UNDRR 2025 HIPs**
`hazard type` = 'meteorological-and-hydrological'
`hazard label` = 'Fluvial (Riverine) Flooding'
`hazard identifier` = 'MH0604' 

**EM-DAT Disaster Classification System**
`Type` = 'Flood'
`Subtype` = 'Riverine flood'
`Classification Key` = 'nat-hyd-flo-riv' 

- `asset category` = 'Buildings'

- `asset dimension` = 'Structure'

- `impact type` = 'Direct'

- `impact modelling` = 'Simulated'
From previous exchanges we were told that "disaster risk" information have to be captured as Loss with the field "impact modelling" (aka. [data_calculation_type](https://docs.riskdatalibrary.org/en/latest/reference/codelists/#data-calculation-type)) set to "simulated"

- `impact metric` = ???
While 'impact metric' includes codes 'at_risk_value' and 'at_risk_tail_value' the definitions do not fully align with what the outputs of "disaster risk" (simulated). We were thus unable to fill this field

- `quantity kind` = ???
The possible codes are 'area', 'count', 'currency', 'length'
While probability disaster risk computation (simulated) rely on quantifiable Average Annual Loss (AAL) or expected annual loss (EAL) data final risk values are often unit less (see for example risk score of FEMA National Risk Index  Zuzak, C., Mowrer, M., Goodenough, E. et al. The national risk index: establishing a nationwide baseline for natural hazard risk in the US. Nat Hazards 114, 2331–2355 (2022). https://doi.org/10.1007/s11069-022-05474-w)
It is unclear which code should then be selected?

- `loss type`
The loss type field is mandatory nevertheless it is hard to understand which code should be used when referring to "disaster risk" as the code refer to loss

- `loss approach` = 'analytical'

- `loss frequency` = 'probabilistic'

------------------------------------------------------------------------------------------------------------------------

Users should be clearly informed which specific field(s) distinguish between “losses” (observed or simulated) and “disaster risk” (simulated only). This distinction needs to be explicitly documented in the public-facing documentation.

**Comment by stufraser1** [comment]
Thank you @samroeslin. 

We are adding hazards to the [`classification` object](https://docs.riskdatalibrary.org/en/latest/reference/schema/#classification), where we enable users to add additional mapping schemes, see the [codelist](https://docs.riskdatalibrary.org/en/latest/reference/codelists/#classification-scheme). We do not intend to replace hazard_type or process_type with multiple optional types, since there are a lot of fields reliant on those codes - we need to define and use one default scheme and codelist there.

- addition: add [EMDAT disaster classification scheme](https://doc.emdat.be/docs/data-structure-and-content/disaster-classification-system/) - in the same way as we're adding HIPS as a classification - see https://github.com/GFDRR/rdl-standard/issues/293#issuecomment-3966172532. We already include disaster identifier but not the disaster / hazards reference.


There is a proposal to add a field to better reference the type of loss/risk data, see https://github.com/GFDRR/rdl-standard/issues/6#issuecomment-3973299395

**Comment by matamadio** [comment]
Thanks for the detailed feedback, adding a few updates:

> Users should be clearly informed which specific field(s) distinguish between “losses” (observed or simulated) and “disaster risk” (simulated only). This distinction needs to be explicitly documented in the public-facing documentation.

Agree, we plan to add detailed information directly in the schema field descriptor, to be rendered in the editor e.g.

<img width="596" height="337" alt="Image" src="https://github.com/user-attachments/assets/596ebf70-bcdd-41b4-ad66-a099873957f3" />

> **UNDRR 2025 HIPs** `hazard type` = 'meteorological-and-hydrological' `hazard label` = 'Fluvial (Riverine) Flooding' `hazard identifier` = 'MH0604'
> 
> **EM-DAT Disaster Classification System** `Type` = 'Flood' `Subtype` = 'Riverine flood' `Classification Key` = 'nat-hyd-flo-riv'

As from Stu's answe, we are mapping all covered hazards (and a few additional ones) to corresponding hips and emdat codes.
Ideally, the user could either select type > process or enter the code > the editor will match the mapping in the type/process selectors.

> * `impact metric` = ???
>   While 'impact metric' includes codes 'at_risk_value' and 'at_risk_tail_value' the definitions do not fully align with what the outputs of "disaster risk" (simulated). We were thus unable to fill this field

What would be the exact metric to use for that case? We can add it to the codelist.

> * `quantity kind` = ???
>   The possible codes are 'area', 'count', 'currency', 'length'
>   While probability disaster risk computation (simulated) rely on quantifiable Average Annual Loss (AAL) or expected annual loss (EAL) data final risk values are often unit less (see for example risk score of FEMA National Risk Index  Zuzak, C., Mowrer, M., Goodenough, E. et al. The national risk index: establishing a nationwide baseline for natural hazard risk in the US. Nat Hazards 114, 2331–2355 (2022). https://doi.org/10.1007/s11069-022-05474-w)
>   It is unclear which code should then be selected?

Quantity kind is currently an open codelist, so any value can be typed in addition to existing options.
On v1.0 it will include a curated list of pertinent options from standard vocabulary: https://www.qudt.org/doc/DOC_VOCAB-QUANTITY-KINDS.html

> * `loss type`
>   The loss type field is mandatory nevertheless it is hard to understand which code should be used when referring to "disaster risk" as the code refer to loss
> * `loss approach` = 'analytical'
> * `loss frequency` = 'probabilistic'

We'll make this clear in the description/examples.

**Comment by stufraser1** [comment]
> What would be the exact metric to use for that case? We can add it to the codelist.

Codelist [impact_metric ](https://github.com/GFDRR/rdl-standard/blob/1.0-dev/schema/codelists/open/impact_metric.csv) 
includes 'Annual Average Loss' which is the more common expression of Expected Annual Loss. It also include Probable Maximum Loss, covering the case of datasets showing return period losses. I don't see that there is anything else needed for the example we're referring to.



> Final risk values are often unit less (though this doesn't relate directly to the flood risk example focussed on in this issue.

Codelist [IMT](https://github.com/GFDRR/rdl-standard/blob/1.0-dev/schema/codelists/open/IMT.csv) in v1.0 includes the `Risk score` - 'Composite risk quantification.' This can be used with [impact metric](https://github.com/GFDRR/rdl-standard/blob/1.0-dev/schema/codelists/open/impact_metric.csv) `Risk Index`

> It is unclear which `quantity kind` code should then be selected

Codelist [quantity_kind
](https://github.com/GFDRR/rdl-standard/blob/1.0-dev/schema/codelists/open/quantity_kind.csv) includes `dimensionless_ratio` - 'A ratio of two quantities of the same kind, e.g. a percentage.' Perhaps @matamadio we need to make this instead (see https://github.com/GFDRR/rdl-standard/pull/403):
`ratio, Ratio, A dimensionless ratio of two quantities of the same kind, e.g. a percentage.`
`index, Index, A dimensionless index such as a hazard, vulnerability, or risk index or score that has been used to classify levels of hazard, vulnerability, or risk.`

**Comment by matamadio** [comment]
We can close this conversation and continue the proposal on detailed components descriptions on #417.
