### ISSUE TITLE
[Proposal] Disaster identifier and date in Hazard.event

### ISSUE THREAD

**Issue by odscrachel** [GFDRR/rdl-standard#60]
## What is the context or reason for the change?

Proposal to add a GLIDE number (core standard) to identify historical disasters.

## What is your proposed change?

To create `disaster_identifier` (The GLIDE number associated with this event disaster. A globally unique identification code for the observed or inferred hazard event. GLIDE numbers are available at https://www.glidenumber.net/glide/public/search/search.jsp.) and `disaster_date` (The date the disaster data as identified by it's GLIDE number was collected.)

## Why is this not covered by the existing model?
The existing model does not include a standard id for empirical disaster records.

**Comment by duncandewhurst** [comment]
> `disaster_date` (The date the disaster data as identified by it's GLIDE number was collected.)

Is this the date that the disaster occurred, i.e. the disaster's date in GLIDE, or is it the date that the risk data was collected?

**Comment by stufraser1** [comment]
> > `disaster_date` (The date the disaster data as identified by it's GLIDE number was collected.)
> 
> Is this the date that the disaster occurred, i.e. the disaster's date in GLIDE, or is it the date that the risk data was collected?

This should refer to the disaster occurrencd date. Complicating factor: a disaster can span multiple dates so we would need a start and end field

**Comment by odscrachel** [comment]
Is a `disaster_date` necessary here at top level, as this will be captured elsewhere or users can look up the information based on the glide number?

**Comment by stufraser1** [comment]
Footprint object captures date so not needed at top level

**Comment by stufraser1** [comment]
Confirm whether `disaster_identifier` sits at top-level or in `event` object. It should be located at event, because multiple historical scenarios could be present in one event set.

**Comment by duncandewhurst** [comment]
`event.disaster_identifier` sounds good to me.

**Comment by odscrachel** [comment]
@matamadio are you happy with the above suggestion for `disaster_identifier` to sit under `event`?

**Comment by matamadio** [comment]
Yes, agree.

Example of GLIDE association as in EM-DAT:

Dis No | Year | Seq | Glide | Disaster Type
-- | -- | -- | -- | --
2007-0320-IND | 2007 | 0320 | FL-2007-000096 | Flood
2007-0556-IND | 2007 | 0556 | TC-2007-000208 | Storm
2008-0246-IND | 2008 | 0246 | FL-2008-000089 | Flood
2008-0486-IND | 2008 | 0486 | FL-2008-000145 | Flood
2008-0560-IND | 2008 | 0560 | TC-2008-000237 | Flood
2008-0062-IND | 2008 | 0062 | LS-2008-000007 | Landslide

**Comment by stufraser1** [comment]
The more common use case is surely one event has one glide number? In cases where a glide number is used as above for >1 event, then the multiple events in the event set could have the same GLIDE No.
