### ISSUE TITLE
[Proposal] Hazard event identifier 

### ISSUE THREAD

**Issue by odscrachel** [GFDRR/rdl-standard#69]
## What is your proposed change?

To create a new `id` field within the `event` object that sits within the `hazard` component. The field will have the following attributes

Title | Field name | Description | Type
| ------------- | ------------- | ------------- | ------------- |
Event identifier  | `event.id` | The unique identifier for this event within the event_set. | array

## What is the context or reason for the change?

This event identifier can be referenced elsewhere within RDLS, it will also allow the data to be easily flattened.

**Comment by duncandewhurst** [comment]
Looks good, but I think its type should be string, not array.

**Comment by odscrachel** [comment]
Agree, so it will be:


Title | Field name | Description | Type
| ------------- | ------------- | ------------- | ------------- |
Event identifier  | `event.id` | The unique identifier for this event within the event_set. | string
