### ISSUE TITLE
[Proposal] Hazard event location 

### ISSUE THREAD

**Issue by odscrachel** [GFDRR/rdl-standard#71]
## What is your proposed change?

To create a new `event.geographic_coverage` field within the `event` object that sits within the `hazard` component. The field will have the following attributes

Title | Field name | Description | Type
| ------------- | ------------- | ------------- | ------------- |
Event location  | `event.geographic_coverage` | The names of the geographic areas covered by the event in the modelled scenario(s). | array of strings

## What is the context or reason for the change?

This replaces `event_set.geo_area` from rdl-schema_0_1.json. It was reasoned that this should be at event level e.g. for the same event_set, multiple locations (events) can be modelled. [Spreadsheet link](https://docs.google.com/spreadsheets/d/1zJjNjiZBf5Tk06NnYkBMJxC0d9Q1QfEhla4N57jGc2U/edit?disco=AAAAtm-tyM0)

**Comment by matamadio** [comment]
This would be different from top-level `subnational_coverage`, which gives the summary of all locations (as list).

- subnational_coverage (Location1_name, Location2_name)
  - hazard.event_set.event1.geographic_coverage (Location1_name)
  - hazard.event_set.event2.geographic_coverage (Location2_name)

**Comment by duncandewhurst** [comment]
I think that our modelling and naming conventions for spatial/geographic coverage at the event level should be consistent with our approach at the dataset level. Suggest that we agree the dataset modelling first in https://github.com/GFDRR/rdl-standard/issues/52 and then update this issue.

**Comment by stufraser1** [comment]
Proposal agreed in #52, so moving to agreed and ready.
