### ISSUE TITLE
[Proposal] Hazard Analysis type codelist

### ISSUE THREAD

**Issue by odscrachel** [GFDRR/rdl-standard#72]
## What is your proposed change?

To create a new codelist for field `event_set.analysis_type`. This will also be used by `loss.hazard_analysis_type`. [Spreadsheet link](https://docs.google.com/spreadsheets/d/1zJjNjiZBf5Tk06NnYkBMJxC0d9Q1QfEhla4N57jGc2U/edit?disco=AAAAtqVs02A)

Title | Field name | Description | Type | Codelist
| ------------- | ------------- | ------------- | ------------- | ------------- |
Analysis type  | `event_set.analysis_type` | The type of analysis used by the hazard model: probabilistic (multiple potential events characterised by different intensity and occurrence frequency); deterministic (frequency-independent representation, such as mean, median or max); empirical (obtained from real event observations). | string | probabilistic, deterministic, empirical

**Comment by duncandewhurst** [comment]
Looks good, but we should avoid documenting the codes and their meanings in the field's description. That information should go in the codelist CSV file in order to maintain a single source of truth and avoid things getting out of sync if updates are made in the future.

**Comment by stufraser1** [comment]
analysis_type.csv

Code,Label,Definition
probabilistic,Probabilistic,Probabilistic risk assessment simulates a large number of synthetic events to estimate their likelihood and severity and estimate overall risk.
deterministic,Deterministic,"Deterministic approaches analyse disaster scenarios (e.g., historical or worst-case events) to estimate their impact, but do not consider the full range of possible outcomes and do not quantify the likelihood of each impact."
empirical,Empirical,"Analysis or data relying on observations, such as hazard intensity recorded during a post-event surveys."
