### ISSUE TITLE
[Proposal] Vulnerability category codelist

### ISSUE THREAD

**Issue by odscrachel** [GFDRR/rdl-standard#76]
## What is your proposed change?

To create a new codelist for the field `category` within the vulnerability component. 

Title | Field name | Description | Type | Codelist
| ------------- | ------------- | ------------- | ------------- | ------------- |
Exposure category  | `category` | The category of the assets described in the dataset. | string | population, buildings, infrastructures, agriculture, natural environment

**Comment by stufraser1** [comment]
This was intended as a high level category. Roads, rail, etc would be specified in taxonomy

**Comment by duncandewhurst** [comment]
What is the proposed codelist based on? I'm unclear on the difference between buildings and infrastructure, e.g. would an exposure dataset about schools be classified as buildings or infrastructure?

**Comment by matamadio** [comment]
From the original documentation about exposure, schema.
It is basically the way that [GED4ALL](https://wiki.openstreetmap.org/wiki/GED4ALL) frames it.
![immagine](https://github.com/GFDRR/rdl-standard/assets/44863827/b5044ff9-9908-4408-a822-17682134275f)
Note that:
- we added `Population`
- we split `Agriculture` (crops, livestock) and `Natural environment` (forestry)

**Comment by duncandewhurst** [comment]
Thanks! That makes sense. I've drafted descriptions for the codes based on GED4ALL.

The only one I'm unsure about is 'population'. Please could you provide a description for that code? I also think that 'people' would fit better with the other codes than 'population'.

Is it usual practice in disaster risk management to consider people as an asset? If not, we might need to reword the description of `category`. 

| Code | Title | Description |
| -- | -- | -- |
| population | Population | |
| buildings | Buildings | Residential, commercial and industrial buildings. | 
| infrastructure | Infrastructure | Infrastructure, including transport, communications, energy, water, health and education facilities. |
| agriculture | Agriculture | Agriculture, including crops, livestock and agribusiness. |
| naturalEnvironment | Natural environment | The natural environment, including forestry and other types of vegetation.|

**Comment by stufraser1** [comment]
@matamadio 
I propose to include health and education and other public buildings in buildings with R/C/I.
Of course we refer to schools, hospitals as critical infrastructure, but I would also describe them in an analysis as public buildings. They fit better into buildings conceptually when people think about the asset type, with infrastructure being reserved for systems or network and points that transport, comms, supply infrastructure fall into.

**Comment by matamadio** [comment]
That is true, population isn't strictly a location-fixed "asset", except it is often treated like it is: an indication of the density of exposed value in one place, and driver of the mortality losses in that place.
GED4ALL considers population in a [separate category](https://wiki.openstreetmap.org/wiki/GED4ALL#Socio-Economic).
However that fits more with our Vulnerability - Socio-economic indicators component, in terms of use-case application.
![immagine](https://github.com/GFDRR/rdl-standard/assets/44863827/1299ef28-7767-42f6-b68f-80805b9baacf)

**Comment by matamadio** [comment]
> @matamadio I propose to include health and education and other public buildings in buildings with R/C/I. Of course we refer to schools, hospitals as critical infrastructure, but I would also describe them in an analysis as public buildings. They fit better into buildings conceptually when people think about the asset type, with infrastructure being reserved for systems or network and points that transport, comms, supply infrastructure fall into.

Yes that makes sense, than it would be:

| Code | Title | Description |
| -- | -- | -- |
| population | Population | Population density |
| buildings | Buildings | Residential, commercial, industrial and public-use buildings. | 
| infrastructure | Infrastructure | Lifelines infrastructure, including transport, communications, energy, water. |
| agriculture | Agriculture | Agriculture, including crops, livestock and agribusiness. |
| naturalEnvironment | Natural environment | The natural environment, including forestry and other types of vegetation.|

**Comment by stufraser1** [comment]
Great, I've aded edu and hlth in description to make it clear.

**Comment by duncandewhurst** [comment]
Regarding population density, it still seems not to fit with the other codes to me. If I understood correctly, the purpose of the field and codelist is to categorise what is exposed to risk. So it makes sense to say, for example, "buildings are exposed to risk". It doesn't make sense to say that "population density is exposed to risk" because population density is a measurement rather than an asset. I think that 'people' would be a better fit with the nature of the other codes. Would that work from your perspective?

It still seems a bit odd to describe people as an asset, but that could be addressed by updating the description of `category`.

Otherwise, the changes look good :-)

**Comment by stufraser1** [comment]
Updated description to people

**Comment by odscjen** [comment]
also related to #62 as this codelist will be referenced in `Exposure.category` as well

**Comment by odscjen** [comment]
codelist updated in https://github.com/GFDRR/rdl-standard/pull/101, leaving this issue open as it still needs updating in `Vulnerability`
