### ISSUE TITLE
[Proposal] Reference models and linked datasets at top level

### ISSUE THREAD

**Issue by odscrachel** [GFDRR/rdl-standard#79]
## What is your proposed change?

The proposal is to use the dataset id to other components, instead of a URL, for example:

Title | Field name | Description | 
| ------------- | ------------- | ------------- | 
| Hazard dataset | `hazard_id` | A unique identifier for the hazard dataset used in the modelled scenario(s). 

Previously in rdl-schema_0_1.json this was:

Field name | Description | 
| ------------- | ------------- | 
| `model.hazard_link` | URL of source hazard data 

This will be the same approach for `exposure_id` and `vulnerability_id`

**Comment by matamadio** [comment]
See #63: we can use project ID to link datasets that are part of the same analysis, instead of new additional fields.

**Comment by stufraser1** [comment]
ID is OK for use in same catalog/database. Can we retain url to use where data might be located elsewhere, not in same catalog?

**Comment by matamadio** [comment]
Yes, actually a good idea when referencing global models for thirt party surces.

**Comment by stufraser1** [comment]
We should refer to dataset OR model in the id and URL. It can be both.

Descriptions suggested as follows
"Internal id for the hazard model or dataset".
"Link to the model or dataset external source."

**Comment by duncandewhurst** [comment]
What is the difference between model and dataset in this context? Or, to put it another way, what is `hazard.model.id` identifying if it's not a dataset?

**Comment by matamadio** [comment]
> What is the difference between model and dataset in this context? Or, to put it another way, what is `hazard.model.id` identifying if it's not a dataset?

That is aimed to identify the model that produced the dataset, e.g.:

```
- Fathom flood hazard model
  - Ghana river flood hazard dataset 
```

In other words, one model can be the source for several datasets. The `model.id` field will allow to group datasets that are parts of the same model.

**Comment by duncandewhurst** [comment]
In that case, I'm a little unsure about @stufraser1's suggestion in https://github.com/GFDRR/rdl-standard/issues/79#issuecomment-1564290403 to use `hazard.model.id` and `hazard.model.url` to identify models or datasets. What if a publisher wants to disclose both the hazard model and the hazard dataset that were used to produce the loss data?

**Comment by stufraser1** [comment]
Thinking more on this, in RDLS we are not hosting, describing or curating a record of disaster risk models.

So, the ID should be unique to a _dataset_ in the catalogue. The URL should allow us to link to an external dataset.
This would be the proposed `hazard_id` for hazard datasets.

We don't need `model.id` because we are not hosting, describing or curating a record of a disaster risk model like we are datasets. However, we should be able to note the name and description of a model used in the analysis to generate the dataset. This would use `model.name`, and `model.description`
I think `model.url` is optional, and could be used to link to a website of the model provider, but is not necessary as this could be included in the description. Possibly bloats the standard unnecessarily.

**Comment by odscjen** [comment]
This discussion has crept away from just identifying the datasets that have been used to create the loss dataset.

I'll create a new issue to record discussion of using `model.name` and `model.description` https://github.com/GFDRR/rdl-standard/issues/85

**Comment by duncandewhurst** [comment]
Thanks for the clarification. With regard to referencing the hazard datasets that were used to create a loss dataset, I have two questions:

1. Is there always a 1:1 relationship between a loss dataset and the hazard dataset that was used to create it, or could more than one hazard dataset be used to create a loss dataset?
1. Does the relationship between the loss dataset and the hazard dataset that was used to create it fit the semantics of [prov:wasDerivedFrom](https://www.w3.org/TR/prov-o/#wasDerivedFrom)?

> A derivation is a transformation of an entity into another, an update of an entity resulting in a new one, or the construction of a new entity based on a pre-existing entity.

Since we're talking about referencing related resources, I think that we should reuse the `RelatedResource` definition proposed in https://github.com/GFDRR/rdl-standard/issues/58#issuecomment-1566330429. Its description can be updated for use in both contexts. Once we have the answers to the above questions, we can decide on a suitable type and name for the field that references the definition.

**Comment by matamadio** [comment]
> * Is there always a 1:1 relationship between a loss dataset and the hazard dataset that was used to create it, or could more than one hazard dataset be used to create a loss dataset?

Usually it is 1:1, but we can't exclude that in somme cases more than one hazard dataset could be applied.

> * Does the relationship between the loss dataset and the hazard dataset that was used to create it fit the semantics of [prov:wasDerivedFrom](https://www.w3.org/TR/prov-o/#wasDerivedFrom)?

No, I don't think it fits the definition:

> A derivation is a transformation of an entity into another, an update of an entity resulting in a new one, or the construction of a new entity based on a pre-existing entity.

Loss is the output of an analysis that uses hazard AND the other components combined; we can't say that losses are a translation of hazard IMHO.

> Since we're talking about referencing related resources, I think that we should reuse the RelatedResource definition proposed in https://github.com/GFDRR/rdl-standard/issues/58#issuecomment-1566330429. Its description can be updated for use in both contexts. Once we have the answers to the above questions, we can decide on a suitable type and name for the field that references the definition.

Yes, this seems reasonable.

**Comment by duncandewhurst** [comment]
> Usually it is 1:1, but we can't exclude that in somme cases more than one hazard dataset could be applied.

Okay so in that case our field needs to be an array.

> Loss is the output of an analysis that uses hazard AND the other components combined; we can't say that losses are a translation of hazard IMHO.

Understood. To address both this issue and #85 I propose adding the following fields and codelists. What do you think?

**Fields**

| Field           | Title   | Description                                                                                                           | Type   | Items             |
| --------------- | ------- | --------------------------------------------------------------------------------------------------------------------- | ------ | ----------------- |
| `sources`       | Sources | Related resources that serve as sources of information or predictions that contribute to the creation of the dataset. | array  | `RelatedResource` |
| `sources.type`  | Type    | The nature of the related resource, from the closed resource type codelist.                                           | string |                   |
| `sources.scope` | Scope   | The scope of the related resource, from the closed resource scope codelist.                                           | string |                   |

`sources.type` is based on DCAT's [resource type property](https://www.w3.org/TR/vocab-dcat-3/#Property:resource_type).

**Resource type codelist**

| Code    | Title   | Description                          |
| ------- | ------- | ------------------------------------ |
| dataset | Dataset | Data encoded in a defined structure. |
| model   | Model   | An abstract, conceptual, graphical, mathematical or visualization model that represents empirical objects, phenomena, or physical processes.                                     |

These codes are taken from DataCite's resourceTypeGeneral codelist (see page 48 of the [schema PDF](https://schema.datacite.org/meta/kernel-4.4/doc/DataCite-MetadataKernel_v4.4.pdf)), as recommended in DCAT.

**Resource scope codelist**

| Code          | Title         | Description |
| ------------- | ------------- | ----------- |
| hazard        | Hazard        | ...         |
| exposure      | Exposure      | ...         |
| vulnerability | Vulnerability | ...         |
| loss          | Loss          | ...         |

These codes are based on the key concepts covered in RDLS. I'll need help authoring descriptions for them.

**Example**

A loss dataset that references two sources: a loss model and a hazard dataset.

```json
{
  "sources": [
    {
      "name": "",
      "url": "",
      "type": "model",
      "scope": "loss"      
    },
    {     
      "name": "",
      "url": "",
      "type": "dataset",
      "scope": "hazard"
    }
  ]
}
```

**Comment by matamadio** [comment]
The proposal makes sense, with some comments:

- An alternative to word `scope`, which is too vague: suggesting `sources.component`.
- the model/data definition are correct but must be explained better for use in this speficic case, e.g.
  - **Model**: analytical approach that combines different components' datasets into one output
  - **Dataset**: data representing individual component that is used as input by the model

**Comment by duncandewhurst** [comment]
Those updates sound good to me. Can we move this issue to agreed and ready on the project board?

**Comment by odscjen** [comment]
Noting that "Resource scope codelist" has already been created as "risk_data_ty[e.csv" and is referenced in the top level `ricks_data_type` field.

**Comment by odscjen** [comment]
To remove a level of nesting I'm not going to use `Related_resource` object, instead I'm just going to create `url` and `name` fields within `sources`
