### ISSUE TITLE
How we classify susceptibility layers?

### ISSUE THREAD

**Issue by matamadio** [GFDRR/rdl-standard#8]
I would put them inside hazard schema, as most often they represent susceptibility for hazard to occur, like in the examples below.
However other times, susceptibility refers to damage ratio, so it is used in practice as vulnerability map.

E.g. from AFG geonode
https://disasterrisk.af/layers/geonode:wp4_spl_s3
https://disasterrisk.af/layers/geonode:wp4_spl_s3

**Comment by stufraser1** [comment]
agree it should sit in hazard standard, and we provided an IMT od susceptibility index for landslide to cover this option, without defining the map type elsewhere. I think it would be sufficient to do this way. 
Can hazard_map_type be also confused with observed/modelled map type, or probabilistic/scenario? I think its not clear unless this is exhaustive, but then we risk including enum types that are not strictly comparable / unique.

**Comment by matamadio** [comment]
My proposal (to be included in v0.3) is to add susceptibility as a hazard frequency type:

![immagine](https://user-images.githubusercontent.com/44863827/214551260-ffaa231e-ed2a-43ec-87f6-cd176966f97c.png)
