### ISSUE TITLE
[Proposal] Fragility curves - damage states

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdl-standard#83]
As well as vulnerability curve loss parameters, We need to include the potential to include damage states to handle fragility curves. In the original schema this was a table on its own. 

This possibly needs its own object to include the fields in tables below.

Damage scales represent a set of discrete damage-states, ideally defined by using both text and figures to assess building performance (structural and non-structural) with damage levels classified from no damage to collapse. In this data schema we have included a selection of damage scales that have been widely used seismic risk assessments and post-earthquake damage surveys. We can include a set of commonly used scales to reference.

<img width="632" alt="image" src="https://user-images.githubusercontent.com/12515042/243640605-4918600c-8d0f-4951-b325-021e7ca99daa.png">

<img width="632" alt="image" src="https://user-images.githubusercontent.com/12515042/243640661-c6805d64-d689-46d7-b678-f78fea092373.png">

<img width="632" alt="image" src="https://user-images.githubusercontent.com/12515042/243640748-43bc8dde-e60c-49eb-a447-4688efa5a45a.png">

**Comment by odscjen** [comment]
@stufraser1 Where would this object sit, under `Vulnerability`? Looking at the [metatdata or not spreadsheet](https://docs.google.com/spreadsheets/d/1Zf9tipODj-YydXHqovvf3eCOydZR_XorpRcGB7TpQ8c/edit#gid=0) we'd previously discussed all of the `is_` fields and agreed that they were not metadata and therefore not appropriate for inclusion in the standard. Can you provide a use case where someone looking for a dataset would use this particular data to find it?

**Comment by stufraser1** [comment]
A risk analysis uses exposure data, hazard data and vulnerability data to estimate losses.
In the vulnerability data component, there is a type of relationship called vulnerability function (one curve relating hazard intensity to e.g. loss ratio), and fragility functions which use *a set of say 5 curves* which relate the hazard intensity to the probability of achieving a certain level of damage (for which there would be 5 levels of damage). 

The 5 curves need to stay as a set.

This would be best placed within the vulnerability object.

The question is whether each curve could be represented with the vulnerability object as it is (and we allow people to define `function.type` as fragility (already possible, see https://github.com/GFDRR/rdl-standard/issues/78) and then we allow multiple curves to be related under that function object (this is what I'm not sure about). 
In this issue comment https://github.com/GFDRR/rdl-standard/issues/75#issuecomment-1568223027 I added to `impact_metric` codelist 'probability of exceeding damage limit state', so this would allow us to do this, IF we can link >1 curves to same set, and describe the damage-scales using some of the descriptors in the tables copied above.

**Comment by odscjen** [comment]
@stufraser1 So to make sure I'm understanding this correctly. We're agreeing in #78 to create a `function` object under `vulnerability`. This allows for a range of different `.type`s. e.g.

```json
{
    "vulnerability": {
        "function": {
            "type": "fragility"
        }
    }
}
```

What you're saying here is that this `function` object describes the vulnerability function, and that can be based on a single curve (in the case `type` = "damage-to-loss") OR it can be based on multiple curves (in the case of `type` = "fragility") and we need a way to record the details of every curve which in the case of "fragility" are the damage states?

**Comment by stufraser1** [comment]
> What you're saying here is that this `function` object describes the vulnerability function, and that can be based on a single curve (in the case `type` = "damage-to-loss") OR it can be based on multiple curves (in the case of `type` = "fragility") and we need a way to record the details of every curve which in the case of "fragility" are the damage states?

Yes

**Comment by matamadio** [comment]
IMHO this is more related to data model than metadata.
Also, fragility curves could be multiple, but also singular. Not sure why individual fragility curve would become _damage-to-loss_.

We need to clear up definitions a bit and provide clear examples. [**This paper**](https://link.springer.com/referenceworkentry/10.1007/978-3-642-36197-5_256-1) gives a nice overview of the terms for earthquake hazard, including damage states and more.

> Vulnerability measures loss; fragility measures probability. Vulnerability functions are referred to many ways: damage functions, loss functions, vulnerability curves, and probably others.

However, the boundaries blur when moving to different hazards.

### Fragility curves

Ex. 1 - Flood: phisical impact (ratio) on exposed categories in relation to water level [[Source](https://www.wgtn.ac.nz/sgees/research-centres/documents/riskscape-flood-fragility-methodology.pdf)].
![immagine](https://github.com/GFDRR/rdl-standard/assets/44863827/4c49a419-2e75-4f15-abec-bff1b0ce9e6f)

Ex. 2 - Flood: dam failure probability in relation to water level [[Source](https://ebooks.iospress.nl/pdf/doi/10.3233/978-1-61499-580-7-528)].
![immagine](https://github.com/GFDRR/rdl-standard/assets/44863827/4c3ee132-01ad-43ef-bc17-9d71ce733864)

Ex. 3 - Earthquake: probability of damage in relation to PGA **[[Source](https://link.springer.com/article/10.1007/s10518-021-01063-7)].**
![immagine](https://github.com/GFDRR/rdl-standard/assets/44863827/b2a67a4a-cad5-4b40-af4f-21ab653692e7)


### Damage-to-loss

### Vulnerability

**Comment by matamadio** [comment]
Looking more into the [paper](https://link.springer.com/referenceworkentry/10.1007/978-3-642-36197-5_256-1) to help define `functon.type`:

- fragility curves
- damage-to-loss
- vulnerability

Page 10-11:

> When loss is depicted as a function of environmental excitation, the function can be called a **vulnerability function**.
> A seismic vulnerability function relates uncertain loss to a measure of seismic excitation, such as spectral acceleration response at some damping ratio and period. A seismic vulnerability function usually applies to a particular asset class.
> 
> **Vulnerability is not fragility.**
> **Vulnerability measures loss; fragility measures probability**.

This is the first clear distinction I get for EQ models, although doesn't necessarily matching with the flood terminology - see example 1 on previous comment.

> **Vulnerability functions** are referred to many ways:
> - _damage functions_
> - _loss functions_
> - _vulnerability curves_
> - probably others.

From this, I can't find a place for `damage-to-loss` type.

Some more useful guidance:

> Many vulnerability functions are expressed with conditional probability distributions that give a probability that loss will not exceed some specified value given the excitation, for a particular asset class. The distribution is often assigned a parametric form such as lognormal or beta, in which case the **parameters of the distribution are all required**, some or all of them conditioned on excitation.
 
> When a vulnerability function measures repair cost, it is commonly normalized by replacement cost new (RCN) [...].

> When a vulnerability function measures life-safety impacts, it commonly measures the fraction of indoor occupants who become casualties (that is, they are killed or experience a nonfatal injury to some specified degree) as a function of excitation. There are a variety of human-injury scales, some used by civil engineers and others used by public health professionals.

> Downtime is commonly measured in terms of days or fractions of a year during which the asset cannot be used for its intended purposes.

**Comment by odscjen** [comment]
I'm still not clear on what the use case is for including the damage state names and scale name? Is this something an analyst needs to know at the point of selecting data from a catalogue?

But what it is sounding like is that we need to more thoroughly define what is meant by a `vulnerability.function` within the standard. The description currently agreed in the spreadsheet is:

 > The details of the function used to calculate the impact of the hazard.

But from the pieces quoted from the paper @matamadio shared this doesn't seem sufficient.

And then relating to `function.type`, we've currently got a codelist with 3 codes, fragility, vulnerability, and damage-to-loss. But

> From which I can confirm the distincction between fragility and vulnerability, and interpret that damage-to-loss is a synonym of vulnerability function.

it sounds like vulnerability and damage-to-loss are the same so we should remove one?

And from

> Vulnerability measures loss; fragility measures probability

this brings us back to @stufraser1's original question and should we even be allowing 'fragility' as a `type` of `vulnerability.function` or would it make more sense to split this into 2 objects, one for when it is a vulnerability/damage-to-loss type and one for fragility? In which case we need to change the suggestion in https://github.com/GFDRR/rdl-standard/issues/78

**Comment by stufraser1** [comment]
Let me try to lay out what separate objects could look like

**Comment by stufraser1** [comment]
> > In the vulnerability data component, there is a type of relationship called vulnerability function (one curve relating hazard intensity to e.g. loss ratio), and fragility functions which use a set of say 5 curves which relate the hazard intensity to the probability of achieving a certain level of damage (for which there would be 5 levels of damage).
> 
> And if an analyst was wanting to find a vulnerability dataset to use in their loss calculation would they **need** to know the damage state name and damage scale names for every curve in the vulnerability dataset to judge if a particular vulnerability dataset was suitable for their purpose? @stufraser1

They would need damage scale name to know which damage scale was being used - this wouldn't be easily recorded in a data file. THey should also know how many damage states there are, and ideally the name of the damage states, but the number and names _could_ be in the data file but would be more helpful in the metadata for checking/comparing different datasets.

**Comment by stufraser1** [comment]
> Ex. 1 - Flood: phisical impact (ratio) on exposed categories in relation to water level [[Source](https://www.wgtn.ac.nz/sgees/research-centres/documents/riskscape-flood-fragility-methodology.pdf)].

This Ex 1 is a set of vulnerability curves, despite the image caption. These relate intensity to damage ratio: a vulnerability curve. Editing the examples.

**Comment by stufraser1** [comment]
> Not sure why individual fragility curve would become _damage-to-loss_.

Fragility function gives the probability of achieving a certain damage state, given a level of hazard intensity.
Damage to loss model converts that damage state into a loss ratio.

Example added to https://github.com/GFDRR/rdl-standard/issues/83#issuecomment-1579094612

**Comment by stufraser1** [comment]
> although doesn't necessarily matching with the flood terminology - see example 1 on previous comment.

The RiskScape source report terminology is not correct - the examples shown are vulnerability functions.

> From which I can confirm the distincction between fragility and vulnerability, and interpret that damage-to-loss is a synonym of vulnerability function.

The image is not helpful; it does not present an example of damage-to-loss function. But the paper states:
"Vulnerability curves are derived using a building-level consequence model relating the repair-to-reconstruction cost to structural and non-structural DSs. _Such model requires the definition of the expected building-level damage-to-loss ratios (DLRs) for each DS_. The (mean) LR for a given value of the IM is defined according to equation 2, resulting in a vulnerability relationship."
and
"The loss analysis in the proposed methodology is based on building-level DLRs, to provide a simple solution appropriate for the preliminary (conceptual) design of retrofit alternatives. Appropriately calibrated damage-to-loss ratios (e.g. Martins et al., 2016) are clearly crucial for the accuracy of the solution." Martins et al is the source of the damage-to-loss ratio example above.

In short, it is valid and necessary to provide a solution to describe
1. Vulnerability function (we can include in guidance that these are also called damage functions, etc)
2. Fragility function
3. Damage to Loss function

**Comment by stufraser1** [comment]
Not meaning to hammer to the point too much, but want to make sure all questions are answered:

> Is this something an analyst needs to know at the point of selecting data from a catalogue?

Yes

> But what it is sounding like is that we need to more thoroughly define what is meant by a `vulnerability.function` within the standard.

Yes we do


> From which I can confirm the distincction between fragility and vulnerability, and interpret that damage-to-loss is a synonym of vulnerability function. It sounds like vulnerability and damage-to-loss are the same so we should remove one?

Not correct, we need all three

 
> And from
> > Vulnerability measures loss; fragility measures probability
> this brings us back to @stufraser1's original question and should we even be allowing 'fragility' as a `type` of `vulnerability.function` or would it make more sense to split this into 2 objects, one for when it is a vulnerability/damage-to-loss type and one for fragility? In which case we need to change the suggestion in #78

I think we do need to change the suggestion in #78
Either: 
1. Using THREE objects: `vulnerability.function.vulnerability`, `vulnerability.function.damagetoloss` and `vulnerability.function.fragility`
or
2. Nesting the optional fields for vulnerability, fragility, and damage to loss function under `vulnerability.function` and using `vulnerability.function.type` to denote which is being used
I'll comment there on the proposed structure

Can we close this issue? if we agree on the need to represent 
1. Vulnerability function (we can include in guidance that these are also called damage functions, etc)
3. Fragility function
4. Damage to Loss function

**Comment by matamadio** [comment]
Thanks for the clearing this terminology jungle, Stu.
Damage states are something I'm not used to find for hydromet hazards, but indeed it is mentioned by various source (riskscape, hazus, [research studies](https://www.researchgate.net/publication/237805907_Direct_flood_damage_modeling_towards_urban_flood_risk_management)).
Likely derived from EQ approach.
![immagine](https://github.com/GFDRR/rdl-standard/assets/44863827/8e0e89a3-f6a3-42b3-8feb-c0d6a2ba041a)

Agree they should be three independent objects. Both proposals make sense; maybe the first one is more straightforward, but I'll let ODS suggest the best approach.

**Comment by stufraser1** [comment]
> Likely derived from EQ approach.

Exactly that.

I've proposed in #78 to include the few additional fields in the same `vulnerability.function` object, rather than three separate objects, because I think we only need to add 3 new fields (others are dealt with in our new `referencedBy` and `impact` objects. What maybe remains unclear is for which `function.type` each field should be completed, and I see the value in having three objects to make that clear. 

@odscjen recommendation please.

**Comment by odscjen** [comment]
Thanks for all the explanation @stufraser1, this all makes more sense to me now and it's clear the damage information is needed in the standard :)

> What maybe remains unclear is for which function.type each field should be completed, and I see the value in having three objects to make that clear.

I agree that we should split `function` into 3 sub-objects, so `vulnerability.function.vulnerability`, `vulnerability.function.damage_to_loss` and `vulnerability.function.fragility`. Otherwise the descriptions and guidance might get a bit complex. The description of `function` can make it clear that only one of the sub-objects should be used as appropriate to the function being described.

@stufraser1 can you update the suggestion in https://github.com/GFDRR/rdl-standard/issues/78 and then I think we can close this issue?

**Comment by odscjen** [comment]
Closing as this is covered by the resolution in #78
