### ISSUE TITLE
[Proposal] Reference models and linked datasets at top level

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdl-standard#85]
## What is the context or reason for the change?
The `Loss` object currently includes reference to the hazard dataset that has been used to create the loss dataset but no details on the model used to generate it. This may be of use to an analyst wanting to search for loss datasets produced using specific hazard models.

## Why is this not covered by the existing model?
Currently the only reference to the model used to generate the dataset is in the high level metadata, there is no field to record the model used to generate associated datasets.

## What is your proposed change?

Title | Field name | Description | Type 
-- | -- | -- | -- 
Hazard model | hazard_model_name | The name of the hazard model. | string 
Model name | hazard_model_description | The details of the hazard model of function used to calculate the impact of the hazard for the given exposure values. | string 

This suggestion originated in https://github.com/GFDRR/rdl-standard/issues/79

**Comment by odscjen** [comment]
But the top level metadata already contains `model.title` and `model.date`. If there is a link to the hazard dataset from `loss` using `hazard_id` then that linked dataset will already contain `model.title`. Is duplication of this data necessary? @matamadio @stufraser1

**Comment by matamadio** [comment]
Thanks Jen, that's true. That should be enough to link the two.
We could have (top level):

Field name | Description | Type
-- | -- | --
model | The source model that produced the dataset. | object
model.title | The name of the model that the dataset originated from. | string
model.date | The date this dataset was published. | date-time
model.description | Short description of the model and how is used | string

**Comment by duncandewhurst** [comment]
This seems like another case of referencing a related resource (the hazard model, in this case), for which I suggest we take a consistent approach with https://github.com/GFDRR/rdl-standard/issues/79#issuecomment-1579630520 and https://github.com/GFDRR/rdl-standard/issues/58#issuecomment-1566330429 and reuse the `RelatedResource` object.

Two questions:

1. Does the concept of a source model only apply to hazard datasets or does it apply to other types of risk dataset too?
2. Is there always a 1:1 relationship between a dataset and its source model, or can a dataset have multiple source models?

**Comment by matamadio** [comment]
> Does the concept of a source model only apply to hazard datasets or does it apply to other types of risk dataset too?

The concept of model can apply to all components. Some examples:

- Hazard model (GEM, Fathom)
- Exposure model (GEM, OSM, GHS)
- Vulnerability model (GEM, CLIMADA)
- Loss model (GAR, some CATmodel)

> Is there always a 1:1 relationship between a dataset and its source model, or can a dataset have multiple source models?

There is a n:1 relationship between dataset and model, i.e. more than one dataset can stem from the same model.

**Comment by duncandewhurst** [comment]
In https://github.com/GFDRR/rdl-standard/issues/79#issuecomment-1581764260, I've proposed a top-level `sources` field that should address this issue. Please take a look and let me know what you think.

**Comment by stufraser1** [comment]
So the dataset as a whole will reference its source models and/or source datasets at the top-level.
A dataset containing H, E, V, and Loss datasets would reference the model for each component there?

I think this allows us to do what we need.

Examples:
1. A dataset that used Openquake to generate EQ hazard, using METEOR project exposure data and HAZUS V curves, in the CAPRA loss modelling framework, could be represented as follows:

```json
{
  "sources": [
    {
      "name": "OpenQuake",
      "url": "https://platform.openquake.org/",
      "type": "model",
      "scope": "hazard"      
    },
    {     
      "name": "METEOR",
      "url": "www.meteor-project.org",
      "type": "dataset",
      "scope": "exposure"
    },
    {     
      "name": "HAZUS",
      "url": "www.HAZUS.gov/someVcurvesExample",
      "type": "dataset",
      "scope": "vulnerability"
    },
    {     
      "name": "CAPRA",
      "url": "www.e-capra.com",
      "type": "dataset",
      "scope": "loss"
    }
  ]
}
```

2. An EQ analysis using GEM products only:
```json
{
  "sources": [
    {
      "name": "OpenQuake",
      "url": "https://platform.openquake.org/",
      "type": "model",
      "scope": "hazard"      
    },
    {     
      "name": "GEM Northern Africa Exposure",
      "url": "https://www.globalquakemodel.org/product/northern-africa-exposure",
      "type": "dataset",
      "scope": "exposure"
    },
    {     
      "name": "OpenQuake",
      "url": "https://platform.openquake.org/vulnerability/list?type_of_assessment=1",
      "type": "dataset",
      "scope": "vulnerability"
    },
    {     
      "name": "OpenQuake",
      "url": "https://platform.openquake.org/",
      "type": "dataset",
      "scope": "loss"
    }
  ]
}
```

**Comment by duncandewhurst** [comment]
Yep, that's what I had in mind. Ideally, `url` should point exactly to the resource, e.g. `https://downloads.openquake.org/meteor/level1exposure/AFG_oed_exposure_20200811.zip` rather than `www.meteor-project.org` so we should make sure to do that in any examples we include in the documentation.

**Comment by odscjen** [comment]
This ended up being a duplicate of https://github.com/GFDRR/rdl-standard/issues/79 so I'm closing this as the necessary changes are recorded in #79
