### ISSUE TITLE
[Schema] Minor and structural updates

### ISSUE THREAD

**Issue by odscrachel** [GFDRR/rdl-standard#94]
There are a number of updates that need to be made to the schema to make it valid and to capture the minor changes in the [spreadsheet](https://docs.google.com/spreadsheets/d/1zJjNjiZBf5Tk06NnYkBMJxC0d9Q1QfEhla4N57jGc2U/edit#gid=1409535301). These minor changes will be captured in the changelog.

Changes include, but are not limited to:

- [x] Changing `definitions` to `$defs` to match current JSON schema version
- [x] Add missing definitions to fix errors
- [x] Update field names and descriptions where indicated in the [spreadsheet](https://docs.google.com/spreadsheets/d/1zJjNjiZBf5Tk06NnYkBMJxC0d9Q1QfEhla4N57jGc2U/edit#gid=1409535301)
- [x] Update codelists 
- [x] Update which fields are 'required'
- [x] Check integers are replaced with supported number type
- [x] Remove defs that are no longer referenced 
- [x] Capital formatting in defs

**Comment by duncandewhurst** [comment]
>     * [ ]  Add missing definitions to fix errors

https://github.com/GFDRR/rdl-standard/pull/66 adds empty definitions in order to make the schema valid.

**Comment by duncandewhurst** [comment]
> - [ ] Update field names and descriptions where indicated in the [spreadsheet](https://docs.google.com/spreadsheets/d/1zJjNjiZBf5Tk06NnYkBMJxC0d9Q1QfEhla4N57jGc2U/edit#gid=1409535301)

https://github.com/GFDRR/rdl-standard/pull/66 adds a test to make sure that definitions and properties have titles and descriptions. Presently, many titles and descriptions are missing so the test is commented out. We should enable the test when we go through add titles and descriptions from the spreadsheet to make sure that we don't miss any.

**Comment by odscjen** [comment]
Also include 

- [ ] removal of fields as agreed in this [spreadsheet](https://docs.google.com/spreadsheets/d/1Zf9tipODj-YydXHqovvf3eCOydZR_XorpRcGB7TpQ8c/edit#gid=0)

**Comment by odscjen** [comment]
I've updated the fields and descriptions [spreadsheet](https://docs.google.com/spreadsheets/d/1zJjNjiZBf5Tk06NnYkBMJxC0d9Q1QfEhla4N57jGc2U/edit#gid=1409535301) to note which issues relate to which fields in the original schema. This should hopefully help us ensure we're covering everything that should be covered by this minor changes update

**Comment by duncandewhurst** [comment]
> > * [ ]  Update field names and descriptions where indicated in the [spreadsheet](https://docs.google.com/spreadsheets/d/1zJjNjiZBf5Tk06NnYkBMJxC0d9Q1QfEhla4N57jGc2U/edit#gid=1409535301)
> 
> #109 adds a test to make sure that definitions and properties have titles and descriptions. Presently, many titles and descriptions are missing so the test is commented out. We should enable the test when we go through add titles and descriptions from the spreadsheet to make sure that we don't miss any.

I've created a (draft) PR to enable the test: https://github.com/GFDRR/rdl-standard/pull/128
