### ISSUE TITLE
[Proposal] Hazard nest event_set, event and footprint allowing arrays

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdl-standard#95]
## What is the context or reason for the change?

As currently written the schema has `hazard.event_set`, `hazard.event` and `hazard.footprint_set` all at the same level. But there is a 1:n relationships between `event_set` and `event` and a 1:n relationship between `event` and `footprint_set`. The current model doesn't not reflect this.

## Why is this not covered by the existing model?

Current model doesn't reflect the cardinal relationships and doesn't not allow for multiple versions of each object.

Relevant discussions around this can be found in https://github.com/GFDRR/rdl-standard/issues/59 and #70 

## What is your proposed change?

Nest the 3 objects to reflect their relationship and use array's to allow for multiple of all 3 to be contained in a single dataset.

Field | Title | Description | Type
-- | -- | -- | --
hazard.event_sets` | Event_sets | Information about sets of events | array (`Event_set`)
`event_set.events`| Events | Information about hazard events. | array (`Event`)
`events.footprints`| Footprints | Information about hazard event footprints showing spatial distribution of hazard intensity. | array (`Footprint`)

## Can you provide an example?

```json
{
  "hazard": {
    "event_sets": [
      {
        "id": "eventset1",
        "events": [
          {
            "id": "event1",
            "footprint_set": [
              {
                "id": "footprint1"
              },
              {
                "id": "footprint2"
              }
            ]
          },
          {
            "id": "event2",
            "footprint_set": [
              {
                "id": "footprint3"
              },
              {
                "id": "footprint4"
              }
            ]
          }
        ]
      },
      {
        "id": "eventset2",
        "events": [
          {
            "id": "event3",
            "footprint_set": [
              {
                "id": "footprint5"
              },
              {
                "id": "footprint6"
              }
            ]
          },
          {
            "id": "event4",
            "footprint_set": [
              {
                "id": "footprint7"
              },
              {
                "id": "footprint8"
              }
            ]
          }
        ]
      }
    ]
  }
}
```

**Comment by stufraser1** [comment]
This reflects the original intention of the rdl schema
