### ISSUE TITLE
[Discussion] hazard_type and process_type, where should they sit?

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdl-standard#96]
Currently the schema has the Hazard type in `event_set.hazard_type` and the Process type in `footprint_set.process_type`. But in https://github.com/GFDRR/rdl-standard/issues/91#issuecomment-1592687884 the example given has them both in `event_set`.

Where should they sit? From the discussion linked to I'm assuming we should move `process_type` to `event_set`? @stufraser1 @matamadio is this correct?

**Comment by stufraser1** [comment]
Yes we should move process_type to event_set

**Comment by odscjen** [comment]
Just reviewing #91 and note that `hazard_type` is also being discussed there as part of `event`. So should `process_type` be available in `event` as well as `event_set`

**Comment by odscrachel** [comment]
I've moved `process_type` from `footprint` to `event_set` in #121. @stufraser1 let me know if this also needs to be added to `event` per Jen's last comment.

**Comment by stufraser1** [comment]
> let me know if this also needs to be added to event per Jen's last comment.
yes please add `process_typez to `event`
