### ISSUE TITLE
[Docs update] Guides > rdl-metadata

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdl-standard#99]
> As this page is unfinished, I would remove it for now and put the draft content in a GitHub issue.

_Originally posted by @duncandewhurst in https://github.com/GFDRR/rdl-standard/pull/97#discussion_r1237946520_

Removed reference in docs/guides/index.md until more complete

**Comment by duncandewhurst** [comment]
Closing as superseded by #149
